//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes         = "BearerAuth.Scopes"
	RefreshTokenCookieScopes = "RefreshTokenCookie.Scopes"
)

// AccessTokenResponse defines model for AccessTokenResponse.
type AccessTokenResponse struct {
	// AccessToken Short-lived token for accessing protected endpoints
	AccessToken string `json:"access_token"`
}

// AuthenticationErrorResponse defines model for AuthenticationErrorResponse.
type AuthenticationErrorResponse = ErrorResponse

// CreateSessionErrorResponse defines model for CreateSessionErrorResponse.
type CreateSessionErrorResponse = ErrorResponse

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	IsAdmin  bool   `json:"is_admin,omitempty"`
	Password string `json:"password"`

	// Username Must be unique
	Username string `json:"username"`
}

// EmptyResponse defines model for EmptyResponse.
type EmptyResponse = empty

// EntityNotFoundErrorResponse defines model for EntityNotFoundErrorResponse.
type EntityNotFoundErrorResponse = ErrorResponse

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	ErrorBody struct {
		// Type Identifier of the error type
		Type string `json:"type"`

		// StatusCode HTTP status code
		StatusCode int32 `json:"status_code"`

		// Message Error message
		Message string `json:"message,omitempty"`
	} `json:"error"`
}

// MediaUploadFinalizeErrorResponse defines model for MediaUploadFinalizeErrorResponse.
type MediaUploadFinalizeErrorResponse = ErrorResponse

// PingResponse defines model for PingResponse.
type PingResponse struct {
	// Instance Name of the server instance
	Instance string `json:"instance"`

	// ServerTime Server time
	ServerTime time.Time `json:"server_time"`
}

// RefreshSessionErrorResponse defines model for RefreshSessionErrorResponse.
type RefreshSessionErrorResponse = ErrorResponse

// RoleRequiredErrorResponse defines model for RoleRequiredErrorResponse.
type RoleRequiredErrorResponse = ErrorResponse

// TimeoutErrorResponse defines model for TimeoutErrorResponse.
type TimeoutErrorResponse = ErrorResponse

// UUID defines model for UUID.
type UUID = uuid.UUID

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt time.Time `json:"created_at"`
	IsAdmin   bool      `json:"is_admin"`

	// Username Must be unique
	Username string `json:"username"`
	UUID     UUID   `json:"uuid"`
}

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse = ErrorResponse

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

type CreateSessionRequestObject struct {
	Body *CreateSessionJSONRequestBody
}

type CreateSessionResponseObject interface {
	VisitCreateSessionResponse(w http.ResponseWriter) error
}

func (r AccessTokenResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type RefreshSessionRequestObject struct {
}

type RefreshSessionResponseObject interface {
	VisitRefreshSessionResponse(w http.ResponseWriter) error
}

func (r AccessTokenResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type RevokeSessionRequestObject struct {
	SessionID UUID `json:"session_id"`
}

type RevokeSessionResponseObject interface {
	VisitRevokeSessionResponse(w http.ResponseWriter) error
}

func (r EmptyResponse) VisitRevokeSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type PingRequestObject struct {
}

type PingResponseObject interface {
	VisitPingResponse(w http.ResponseWriter) error
}

func (r PingResponse) VisitPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

func (r UserResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type DeactivateUserRequestObject struct {
	UserUUID UUID `json:"user_uuid"`
}

type DeactivateUserResponseObject interface {
	VisitDeactivateUserResponse(w http.ResponseWriter) error
}

func (r EmptyResponse) VisitDeactivateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

// HandlerInterface represents all server handlers.
type HandlerInterface interface {
	// Create a new session
	// (POST /auth/sessions)
	CreateSession(w http.ResponseWriter, r *http.Request, request CreateSessionRequestObject) (CreateSessionResponseObject, error)
	// Refresh the current session
	// (POST /auth/sessions/refresh)
	RefreshSession(w http.ResponseWriter, r *http.Request, request RefreshSessionRequestObject) (RefreshSessionResponseObject, error)
	// Revoke a session
	// (POST /auth/sessions/{session_id}/revoke)
	RevokeSession(w http.ResponseWriter, r *http.Request, request RevokeSessionRequestObject) (RevokeSessionResponseObject, error)
	// Ping the API server
	// (GET /ping)
	Ping(w http.ResponseWriter, r *http.Request, request PingRequestObject) (PingResponseObject, error)
	// Create a user
	// (POST /users)
	CreateUser(w http.ResponseWriter, r *http.Request, request CreateUserRequestObject) (CreateUserResponseObject, error)
	// Deactivate a user
	// (POST /users/{user_uuid}/deactivate)
	DeactivateUser(w http.ResponseWriter, r *http.Request, request DeactivateUserRequestObject) (DeactivateUserResponseObject, error)
}

// HandlerInterfaceWrapper converts contexts to parameters.
type HandlerInterfaceWrapper struct {
	handler HandlerInterface
	options Options
}

// CreateSession operation middleware
func (hiw *HandlerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	var request CreateSessionRequestObject

	var body CreateSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	response, err := hiw.handler.CreateSession(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitCreateSessionResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// RefreshSession operation middleware
func (hiw *HandlerInterfaceWrapper) RefreshSession(w http.ResponseWriter, r *http.Request) {

	var request RefreshSessionRequestObject

	response, err := hiw.handler.RefreshSession(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitRefreshSessionResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// RevokeSession operation middleware
func (hiw *HandlerInterfaceWrapper) RevokeSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", r.PathValue("session_id"), &sessionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	var request RevokeSessionRequestObject

	request.SessionID = sessionID

	response, err := hiw.handler.RevokeSession(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitRevokeSessionResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// Ping operation middleware
func (hiw *HandlerInterfaceWrapper) Ping(w http.ResponseWriter, r *http.Request) {

	var request PingRequestObject

	response, err := hiw.handler.Ping(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitPingResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// CreateUser operation middleware
func (hiw *HandlerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	response, err := hiw.handler.CreateUser(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitCreateUserResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// DeactivateUser operation middleware
func (hiw *HandlerInterfaceWrapper) DeactivateUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_uuid" -------------
	var userUUID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "user_uuid", r.PathValue("user_uuid"), &userUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_uuid", Err: err})
		return
	}

	var request DeactivateUserRequestObject

	request.UserUUID = userUUID

	response, err := hiw.handler.DeactivateUser(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitDeactivateUserResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(hi HandlerInterface) http.Handler {
	return HandlerWithOptions(hi, Options{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type Options struct {
	BaseURL                  string
	BaseRouter               ServeMux
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

const (
	CreateSessionPath  = "/auth/sessions"
	RefreshSessionPath = "/auth/sessions/refresh"
	RevokeSessionPath  = "/auth/sessions/{session_id}/revoke"
	PingPath           = "/ping"
	CreateUserPath     = "/users"
	DeactivateUserPath = "/users/{user_uuid}/deactivate"
)

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(hi HandlerInterface, options Options) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}

	wrapper := HandlerInterfaceWrapper{
		handler: hi,
		options: options,
	}

	m.HandleFunc("POST "+options.BaseURL+CreateSessionPath, wrapper.CreateSession)
	m.HandleFunc("POST "+options.BaseURL+RefreshSessionPath, wrapper.RefreshSession)
	m.HandleFunc("POST "+options.BaseURL+RevokeSessionPath, wrapper.RevokeSession)
	m.HandleFunc("GET "+options.BaseURL+PingPath, wrapper.Ping)
	m.HandleFunc("POST "+options.BaseURL+CreateUserPath, wrapper.CreateUser)
	m.HandleFunc("POST "+options.BaseURL+DeactivateUserPath, wrapper.DeactivateUser)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa32/jNhL+VwhegXs4Oc5utsVCb26ioL5mbZ/t9FoEOYGRxjYbidSSVJrU0P9+ICnL",
	"+kHbu4VzSa952pU4ImeG8338hs4aRzzNOAOmJPbXWEYrSIn57yCKQMo5vwc2BZlxJkG/zgTPQCgKxogY",
	"o1BpK/0cg4wEzRTlDPt4tuJC9RL6ADEyJmjBBbLfULZEmeAKIgUxAhZnnGonPKyeMsA+lkpQtsRF4WEB",
	"n3MqIMb+TXPF28qa3/0KkcKFhwe5WgFTNCLai0AILur+kyQZL7B/s8bfCFhgH/+tv01Bv4y/3/ys8Npx",
	"gx7vpsM6s8bA8lQ7Ozg/D2azcD7+MRiFo/E8/GlwNbzAXnMg+HkynAYXOhp4JGmW6IB2fFoUOiHtoNet",
	"Nx5+7C15r3zZCua28PC5AKJgpvfhpXM0HJnIwvNpcBGM5sPB1ayZCZfBc6RhCp9zkKrrcUak/I2L2Hhd",
	"uTXLvwMxg2h6NsceTsnjFbClWmH/uw+dGvZwLkEwkprIa7Zn7z2cEaVAaLz854b0fr/9xzcHQVDN5m2d",
	"c2HBxnctQewMjsqQxCkt0bsgeaKwvyCJhGq+O84TIKyezp68p1mPG6CTpGewCwL7SuRQeH8kYyllm8eP",
	"B/LXJJlPuVToDlDO6OdcZ2S7YC1NrZzXVvv2WXcgSDP11MBWHFObtUltH5oJd5Yv6JnMlExR9TTi6pLn",
	"LH5Z8Go8zn8x/HQ5vh61OKwzeiTYdmL+It9TkJIsHRVkpkOb4UYArZFmTXwhHrQZF7F+PCs8LBVRuQwj",
	"Hjtc+WE+nyBrgYyFhxdcpERhH1Omzt5vndArLEHg2vTvq+S25x3G+khcUBCIL5BaATJJQsa6EfHPg0+T",
	"qyAMptPxNJz/Mgn2hd18WXrxro2VcpF64Lc7at1C3Ob9ex4/dXBn91YXwSeIKbnOEk7iS8pIQn+HPVj4",
	"ygqbULbcXWCUSUVY5MjziKSwybAE8QACVcYOVrMmoaIuYpvZ781grQxioqBXvtzPUbWV6wu5aGoKCwFy",
	"9SoEwTS4nAazH2rSZxboA6P7fqOmmiNOObXr4yMx0pQnMC1T/8LZG18F4TT417UjB42hI0U+pynwXL10",
	"ycwm49EsCOfDT8H4et7e+9bokUK/vh5eaC8qaOY5jQ/QpTY5MR/WTw+aZlxYcUa0JsFLqlb53UnE0/6S",
	"82UCfTO3dtuquV3UFBnFF4dENTzbQxpeQwJWWbMnV0sB/lEhZqdvy66uyNMx+vsrxuSuo8Zs4mvBe3WF",
	"VgXoor6fSELjV9ArGj4azIfjUXg5GF61wdsdPkoVm0MoygVVTzMdj/XteyAChO6k9dOdebrc1NI//63Z",
	"2ERvasOMbutqpVRWO1LMBcI55/cU7NGJfRzZRw+Xx72wpmVTX81EMvojaAmga5QteLfkBpMhErAAAeUB",
	"S5XtNMgD5blAg8kQe/gBhLT2pyenJ++0czwDRjKKfXx2cnpyalS8WpnY+yRXq760J6Ht/7htnJpr294K",
	"EcTgN1SaYzOzMNU0jCujWTUqbBtmpI1GK2cKmJmcZFlS3ln0f5WcbW9jDiHC2cQWTYiUfZkod96E9f70",
	"9Gg+uC6LjAvNnFmAbrKFxBY0+MMRvdkFaYdH5Yagh+oTtCA0gdgKZOvZu+fZq4POUWbcQpEAo99JIrdu",
	"fXvEhB30pNSytcU/HG1xp4JwbpUdM4qY52rjTY3CsH9z62GZpykRT7sxqshSmrvExlUhNmzYhH+/pKbd",
	"NFDSnFH8US4EMLVZ6QRVg+byk0oEj0oQc+O5EDxFlghlhzaachy/PHDLNOxA7vHwsa8P+QK3apg9Xn3u",
	"u29x+ATGHDGu0EJ/8IbYA4hdO6XCzW3RgPIenH0dotfl/0IaF30BD/we9qFbjyOy84C3BlugZkSQFBQI",
	"aSIzcsdo+krsbJfH7RPa+8L8lxr49hl5oXlv6dxbk5m/7lG+73cmh3fNynxjqj8PU9UoqEMGe3kn022t",
	"v8ZLcLUPhJlmWWotwAUiaAUkUatoBdF9h2Ym9ibh2eDeuO905EeH0sD4W4UcVp86qea80m2qjaFWMna7",
	"y1LJpTkxDvaa2m5Hk3lth56vw6z/jPg/bi8bd16OzdFpeTuC3o6gv4JYrt/N3ZQ3qy2t3KaLDeVYlqkx",
	"Tn+t/wnzXGvhGEik6ANRe/TwRWWzi4y2FiUhHVbElQ9/akFsOGibw/iNhr6ahs6Od4+w8/c4h0MLLu5o",
	"HMMbJf7/UqKLuDq0uHdeO6HJimWyXCTlzx1+v5/wiCQrLpX/8fTjaZ9kFGv7cgnX7xZ2qr/LUvejikbl",
	"lhlLjVh43b8NsG2366NWL9L9WBOz80ubCO33Y8+kuteg0+bELQtt8OpIpfAw46pncOT099WhXKtonkBv",
	"cw46vX4tPFn9BYvDyxckq8LDJWE4/XpVPLY9op07/TrlQ1EU/w0AAP//PeDVQDkuAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
