//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes         = "BearerAuth.Scopes"
	RefreshTokenCookieScopes = "RefreshTokenCookie.Scopes"
)

// AccessForbiddenErrorResponse defines model for AccessForbiddenErrorResponse.
type AccessForbiddenErrorResponse struct {
	Error struct {
		Type interface{} `json:"type,omitempty"`
	} `json:"error"`
}

// AccessTokenResponse defines model for AccessTokenResponse.
type AccessTokenResponse struct {
	// AccessToken Short-lived token for accessing protected endpoints
	AccessToken string `json:"access_token"`
}

// AddUserToWorkspaceRequest defines model for AddUserToWorkspaceRequest.
type AddUserToWorkspaceRequest struct {
	UserUUID UUID `json:"user_uuid"`
}

// AuthenticationErrorResponse defines model for AuthenticationErrorResponse.
type AuthenticationErrorResponse = ErrorResponse

// CreateSecretRequest defines model for CreateSecretRequest.
type CreateSecretRequest = SecretRequestCommon

// CreateSessionErrorResponse defines model for CreateSessionErrorResponse.
type CreateSessionErrorResponse = ErrorResponse

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	IsAdmin  bool   `json:"is_admin,omitempty"`
	Password string `json:"password"`

	// Username Must be unique
	Username string `json:"username"`
}

// CreateWorkspaceRequest defines model for CreateWorkspaceRequest.
type CreateWorkspaceRequest = WorkspaceRequestCommon

// EmptyResponse defines model for EmptyResponse.
type EmptyResponse = empty

// EntityNotFoundErrorResponse defines model for EntityNotFoundErrorResponse.
type EntityNotFoundErrorResponse = ErrorResponse

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	ErrorBody struct {
		// Type Identifier of the error type
		Type string `json:"type"`

		// StatusCode HTTP status code
		StatusCode int32 `json:"status_code"`

		// Message Error message
		Message string `json:"message,omitempty"`
	} `json:"error"`
}

// MediaUploadFinalizeErrorResponse defines model for MediaUploadFinalizeErrorResponse.
type MediaUploadFinalizeErrorResponse = ErrorResponse

// PingResponse defines model for PingResponse.
type PingResponse struct {
	// Instance Name of the server instance
	Instance string `json:"instance"`

	// ServerTime Server time
	ServerTime time.Time `json:"server_time"`
}

// RefreshSessionErrorResponse defines model for RefreshSessionErrorResponse.
type RefreshSessionErrorResponse = ErrorResponse

// RoleRequiredErrorResponse defines model for RoleRequiredErrorResponse.
type RoleRequiredErrorResponse = ErrorResponse

// SecretRequestCommon defines model for SecretRequestCommon.
type SecretRequestCommon struct {
	Name string `json:"name"`

	// Value Secret value to store. It'll be encrypted and never displayed as is
	Value string `json:"value"`
}

// SecretResponse defines model for SecretResponse.
type SecretResponse struct {
	AuthorUUID UUID      `json:"author_uuid"`
	CreatedAt  time.Time `json:"created_at"`
	Name       string    `json:"name"`
	UUID       UUID      `json:"uuid"`
}

// TimeoutErrorResponse defines model for TimeoutErrorResponse.
type TimeoutErrorResponse = ErrorResponse

// UUID defines model for UUID.
type UUID = uuid.UUID

// UpdateSecretRequest defines model for UpdateSecretRequest.
type UpdateSecretRequest = SecretRequestCommon

// UpdateWorkspaceRequest defines model for UpdateWorkspaceRequest.
type UpdateWorkspaceRequest = WorkspaceRequestCommon

// UserAlreadyExistsErrorResponse defines model for UserAlreadyExistsErrorResponse.
type UserAlreadyExistsErrorResponse = ErrorResponse

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt time.Time `json:"created_at"`
	IsAdmin   bool      `json:"is_admin"`
	Username  string    `json:"username"`
	UUID      UUID      `json:"uuid"`
}

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse = ErrorResponse

// WorkspaceRequestCommon defines model for WorkspaceRequestCommon.
type WorkspaceRequestCommon struct {
	Name string `json:"name"`
}

// WorkspaceResponse defines model for WorkspaceResponse.
type WorkspaceResponse struct {
	CreatedAt time.Time `json:"created_at"`
	Name      string    `json:"name"`
	UUID      UUID      `json:"uuid"`
}

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// CreateWorkspaceJSONRequestBody defines body for CreateWorkspace for application/json ContentType.
type CreateWorkspaceJSONRequestBody = CreateWorkspaceRequest

// UpdateWorkspaceJSONRequestBody defines body for UpdateWorkspace for application/json ContentType.
type UpdateWorkspaceJSONRequestBody = UpdateWorkspaceRequest

// CreateSecretJSONRequestBody defines body for CreateSecret for application/json ContentType.
type CreateSecretJSONRequestBody = CreateSecretRequest

// UpdateSecretJSONRequestBody defines body for UpdateSecret for application/json ContentType.
type UpdateSecretJSONRequestBody = UpdateSecretRequest

// AddUserToWorkspaceJSONRequestBody defines body for AddUserToWorkspace for application/json ContentType.
type AddUserToWorkspaceJSONRequestBody = AddUserToWorkspaceRequest

type CreateSessionRequestObject struct {
	Body *CreateSessionJSONRequestBody
}

type CreateSessionResponseObject interface {
	VisitCreateSessionResponse(w http.ResponseWriter) error
}

func (r AccessTokenResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type RefreshSessionRequestObject struct {
}

type RefreshSessionResponseObject interface {
	VisitRefreshSessionResponse(w http.ResponseWriter) error
}

func (r AccessTokenResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type RevokeSessionRequestObject struct {
	SessionID UUID `json:"session_id"`
}

type RevokeSessionResponseObject interface {
	VisitRevokeSessionResponse(w http.ResponseWriter) error
}

func (r EmptyResponse) VisitRevokeSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type PingRequestObject struct {
}

type PingResponseObject interface {
	VisitPingResponse(w http.ResponseWriter) error
}

func (r PingResponse) VisitPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

func (r UserResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type DeactivateUserRequestObject struct {
	UserUUID UUID `json:"user_uuid"`
}

type DeactivateUserResponseObject interface {
	VisitDeactivateUserResponse(w http.ResponseWriter) error
}

func (r EmptyResponse) VisitDeactivateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type CreateWorkspaceRequestObject struct {
	Body *CreateWorkspaceJSONRequestBody
}

type CreateWorkspaceResponseObject interface {
	VisitCreateWorkspaceResponse(w http.ResponseWriter) error
}

func (r WorkspaceResponse) VisitCreateWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type UpdateWorkspaceRequestObject struct {
	WorkspaceUUID UUID `json:"workspace_uuid"`
	Body          *UpdateWorkspaceJSONRequestBody
}

type UpdateWorkspaceResponseObject interface {
	VisitUpdateWorkspaceResponse(w http.ResponseWriter) error
}

func (r WorkspaceResponse) VisitUpdateWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type CreateSecretRequestObject struct {
	WorkspaceUUID UUID `json:"workspace_uuid"`
	Body          *CreateSecretJSONRequestBody
}

type CreateSecretResponseObject interface {
	VisitCreateSecretResponse(w http.ResponseWriter) error
}

func (r SecretResponse) VisitCreateSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type UpdateSecretRequestObject struct {
	WorkspaceUUID UUID `json:"workspace_uuid"`
	SecretUUID    UUID `json:"secret_uuid"`
	Body          *UpdateSecretJSONRequestBody
}

type UpdateSecretResponseObject interface {
	VisitUpdateSecretResponse(w http.ResponseWriter) error
}

func (r SecretResponse) VisitUpdateSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type AddUserToWorkspaceRequestObject struct {
	WorkspaceUUID UUID `json:"workspace_uuid"`
	Body          *AddUserToWorkspaceJSONRequestBody
}

type AddUserToWorkspaceResponseObject interface {
	VisitAddUserToWorkspaceResponse(w http.ResponseWriter) error
}

func (r EmptyResponse) VisitAddUserToWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type RemoveUserFromWorkspaceRequestObject struct {
	WorkspaceUUID UUID `json:"workspace_uuid"`
	UserUUID      UUID `json:"user_uuid"`
}

type RemoveUserFromWorkspaceResponseObject interface {
	VisitRemoveUserFromWorkspaceResponse(w http.ResponseWriter) error
}

func (r EmptyResponse) VisitRemoveUserFromWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(204)

	return json.NewEncoder(w).Encode(r)
}

// HandlerInterface represents all server handlers.
type HandlerInterface interface {
	// Create a new session
	// (POST /auth/sessions)
	CreateSession(w http.ResponseWriter, r *http.Request, request CreateSessionRequestObject) (CreateSessionResponseObject, error)
	// Refresh the current session
	// (POST /auth/sessions/refresh)
	RefreshSession(w http.ResponseWriter, r *http.Request, request RefreshSessionRequestObject) (RefreshSessionResponseObject, error)
	// Revoke a session
	// (POST /auth/sessions/{session_id}/revoke)
	RevokeSession(w http.ResponseWriter, r *http.Request, request RevokeSessionRequestObject) (RevokeSessionResponseObject, error)
	// Ping the API server
	// (GET /ping)
	Ping(w http.ResponseWriter, r *http.Request, request PingRequestObject) (PingResponseObject, error)
	// Create a user
	// (POST /users)
	CreateUser(w http.ResponseWriter, r *http.Request, request CreateUserRequestObject) (CreateUserResponseObject, error)
	// Deactivate a user
	// (POST /users/{user_uuid}/deactivate)
	DeactivateUser(w http.ResponseWriter, r *http.Request, request DeactivateUserRequestObject) (DeactivateUserResponseObject, error)
	// Create a workspace
	// (POST /workspaces)
	CreateWorkspace(w http.ResponseWriter, r *http.Request, request CreateWorkspaceRequestObject) (CreateWorkspaceResponseObject, error)
	// Update a workspace
	// (PUT /workspaces/{workspace_uuid})
	UpdateWorkspace(w http.ResponseWriter, r *http.Request, request UpdateWorkspaceRequestObject) (UpdateWorkspaceResponseObject, error)
	// Create a secret
	// (POST /workspaces/{workspace_uuid}/secrets)
	CreateSecret(w http.ResponseWriter, r *http.Request, request CreateSecretRequestObject) (CreateSecretResponseObject, error)
	// Update a secret
	// (PUT /workspaces/{workspace_uuid}/secrets/{secret_uuid})
	UpdateSecret(w http.ResponseWriter, r *http.Request, request UpdateSecretRequestObject) (UpdateSecretResponseObject, error)
	// Add a user to a workspace
	// (POST /workspaces/{workspace_uuid}/users)
	AddUserToWorkspace(w http.ResponseWriter, r *http.Request, request AddUserToWorkspaceRequestObject) (AddUserToWorkspaceResponseObject, error)
	// Remove a user from a workspace
	// (DELETE /workspaces/{workspace_uuid}/users/{user_uuid})
	RemoveUserFromWorkspace(w http.ResponseWriter, r *http.Request, request RemoveUserFromWorkspaceRequestObject) (RemoveUserFromWorkspaceResponseObject, error)
}

// HandlerInterfaceWrapper converts contexts to parameters.
type HandlerInterfaceWrapper struct {
	handler HandlerInterface
	options Options
}

// CreateSession operation middleware
func (hiw *HandlerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	var request CreateSessionRequestObject

	var body CreateSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	response, err := hiw.handler.CreateSession(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitCreateSessionResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// RefreshSession operation middleware
func (hiw *HandlerInterfaceWrapper) RefreshSession(w http.ResponseWriter, r *http.Request) {

	var request RefreshSessionRequestObject

	response, err := hiw.handler.RefreshSession(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitRefreshSessionResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// RevokeSession operation middleware
func (hiw *HandlerInterfaceWrapper) RevokeSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", r.PathValue("session_id"), &sessionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	var request RevokeSessionRequestObject

	request.SessionID = sessionID

	response, err := hiw.handler.RevokeSession(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitRevokeSessionResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// Ping operation middleware
func (hiw *HandlerInterfaceWrapper) Ping(w http.ResponseWriter, r *http.Request) {

	var request PingRequestObject

	response, err := hiw.handler.Ping(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitPingResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// CreateUser operation middleware
func (hiw *HandlerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	response, err := hiw.handler.CreateUser(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitCreateUserResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// DeactivateUser operation middleware
func (hiw *HandlerInterfaceWrapper) DeactivateUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_uuid" -------------
	var userUUID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "user_uuid", r.PathValue("user_uuid"), &userUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_uuid", Err: err})
		return
	}

	var request DeactivateUserRequestObject

	request.UserUUID = userUUID

	response, err := hiw.handler.DeactivateUser(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitDeactivateUserResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// CreateWorkspace operation middleware
func (hiw *HandlerInterfaceWrapper) CreateWorkspace(w http.ResponseWriter, r *http.Request) {

	var request CreateWorkspaceRequestObject

	var body CreateWorkspaceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	response, err := hiw.handler.CreateWorkspace(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitCreateWorkspaceResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// UpdateWorkspace operation middleware
func (hiw *HandlerInterfaceWrapper) UpdateWorkspace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspace_uuid" -------------
	var workspaceUUID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "workspace_uuid", r.PathValue("workspace_uuid"), &workspaceUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_uuid", Err: err})
		return
	}

	var request UpdateWorkspaceRequestObject

	request.WorkspaceUUID = workspaceUUID

	var body UpdateWorkspaceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	response, err := hiw.handler.UpdateWorkspace(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitUpdateWorkspaceResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// CreateSecret operation middleware
func (hiw *HandlerInterfaceWrapper) CreateSecret(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspace_uuid" -------------
	var workspaceUUID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "workspace_uuid", r.PathValue("workspace_uuid"), &workspaceUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_uuid", Err: err})
		return
	}

	var request CreateSecretRequestObject

	request.WorkspaceUUID = workspaceUUID

	var body CreateSecretJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	response, err := hiw.handler.CreateSecret(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitCreateSecretResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// UpdateSecret operation middleware
func (hiw *HandlerInterfaceWrapper) UpdateSecret(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspace_uuid" -------------
	var workspaceUUID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "workspace_uuid", r.PathValue("workspace_uuid"), &workspaceUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_uuid", Err: err})
		return
	}

	// ------------- Path parameter "secret_uuid" -------------
	var secretUUID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "secret_uuid", r.PathValue("secret_uuid"), &secretUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "secret_uuid", Err: err})
		return
	}

	var request UpdateSecretRequestObject

	request.WorkspaceUUID = workspaceUUID
	request.SecretUUID = secretUUID

	var body UpdateSecretJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	response, err := hiw.handler.UpdateSecret(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitUpdateSecretResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// AddUserToWorkspace operation middleware
func (hiw *HandlerInterfaceWrapper) AddUserToWorkspace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspace_uuid" -------------
	var workspaceUUID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "workspace_uuid", r.PathValue("workspace_uuid"), &workspaceUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_uuid", Err: err})
		return
	}

	var request AddUserToWorkspaceRequestObject

	request.WorkspaceUUID = workspaceUUID

	var body AddUserToWorkspaceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	response, err := hiw.handler.AddUserToWorkspace(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitAddUserToWorkspaceResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// RemoveUserFromWorkspace operation middleware
func (hiw *HandlerInterfaceWrapper) RemoveUserFromWorkspace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspace_uuid" -------------
	var workspaceUUID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "workspace_uuid", r.PathValue("workspace_uuid"), &workspaceUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_uuid", Err: err})
		return
	}

	// ------------- Path parameter "user_uuid" -------------
	var userUUID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "user_uuid", r.PathValue("user_uuid"), &userUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_uuid", Err: err})
		return
	}

	var request RemoveUserFromWorkspaceRequestObject

	request.WorkspaceUUID = workspaceUUID
	request.UserUUID = userUUID

	response, err := hiw.handler.RemoveUserFromWorkspace(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitRemoveUserFromWorkspaceResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(hi HandlerInterface) http.Handler {
	return HandlerWithOptions(hi, Options{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type Options struct {
	BaseURL                  string
	BaseRouter               ServeMux
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

const (
	CreateSessionPath           = "/auth/sessions"
	RefreshSessionPath          = "/auth/sessions/refresh"
	RevokeSessionPath           = "/auth/sessions/{session_id}/revoke"
	PingPath                    = "/ping"
	CreateUserPath              = "/users"
	DeactivateUserPath          = "/users/{user_uuid}/deactivate"
	CreateWorkspacePath         = "/workspaces"
	UpdateWorkspacePath         = "/workspaces/{workspace_uuid}"
	CreateSecretPath            = "/workspaces/{workspace_uuid}/secrets"
	UpdateSecretPath            = "/workspaces/{workspace_uuid}/secrets/{secret_uuid}"
	AddUserToWorkspacePath      = "/workspaces/{workspace_uuid}/users"
	RemoveUserFromWorkspacePath = "/workspaces/{workspace_uuid}/users/{user_uuid}"
)

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(hi HandlerInterface, options Options) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}

	wrapper := HandlerInterfaceWrapper{
		handler: hi,
		options: options,
	}

	m.HandleFunc("POST "+options.BaseURL+CreateSessionPath, wrapper.CreateSession)
	m.HandleFunc("POST "+options.BaseURL+RefreshSessionPath, wrapper.RefreshSession)
	m.HandleFunc("POST "+options.BaseURL+RevokeSessionPath, wrapper.RevokeSession)
	m.HandleFunc("GET "+options.BaseURL+PingPath, wrapper.Ping)
	m.HandleFunc("POST "+options.BaseURL+CreateUserPath, wrapper.CreateUser)
	m.HandleFunc("POST "+options.BaseURL+DeactivateUserPath, wrapper.DeactivateUser)
	m.HandleFunc("POST "+options.BaseURL+CreateWorkspacePath, wrapper.CreateWorkspace)
	m.HandleFunc("PUT "+options.BaseURL+UpdateWorkspacePath, wrapper.UpdateWorkspace)
	m.HandleFunc("POST "+options.BaseURL+CreateSecretPath, wrapper.CreateSecret)
	m.HandleFunc("PUT "+options.BaseURL+UpdateSecretPath, wrapper.UpdateSecret)
	m.HandleFunc("POST "+options.BaseURL+AddUserToWorkspacePath, wrapper.AddUserToWorkspace)
	m.HandleFunc("DELETE "+options.BaseURL+RemoveUserFromWorkspacePath, wrapper.RemoveUserFromWorkspace)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcbXPbNhL+KxhcZ/rhKMuJ005G3xSbvurq2B5JbpPx+DQwuZJQkwQDgI5Vjf77DQCS",
	"4gsoKYn8kpTfLGEBLBa7D55dQF5ij4UxiyCSAveWWHhzCIn+s+95IMQp47fU9yFyOWd8CCJmkQDVToLg",
	"Yop710v8E4cp7uF/dddjddOBuuVuK2eJY85i4JKCngVUu/qj/LVcxHoSiJIQ965x//jYHY0mpxfDd4OT",
	"E/cc3zgYHkgYB4B79dbVarVy0kEwu/0LPIlXNysnXdSY3UFUXEt5cqKFJlJJqc8+CI/TWFIW4R4ezRmX",
	"nYDeg4+0CJoyjkwfGs1QzJkET4KPIPJjRpVlc12E5DSaYaUdh08J5eCr5ZVmvKlp7uC+718J4GP2J+N3",
	"IiYeDOFTAkLWtU8E8EmSUF992LQ1V1eDk5om695WNRI5h0hSjyhjvAiXGF/87p5Pzi/Gkz/6Z4MT7JQb",
	"3A+Xg6F7YvWXaler1zjLyjcOfujMWCf9srIY5WPHHIiEEXgcZOMuRSQ0q8mV+g9jswBQ/3KA7mCBHRyS",
	"hzOIZnKOe7++cXBIo+zjm5o/OfieBAlYvFWrgXQrkgwJyTgcoIH8OQjQLSCIPL6IlbeSyEcR3ANHPhVx",
	"QBbqO4Go8t61luFiIvSQEzNhSa9X2/xcrzrT1eZgme2EeHb/Gpxrr5gcD90T93w86J+Nyl5kE9izC2kz",
	"NPpQTIT4zLhf9qNR8ivwEXjDo3HdiWpuo+I988WC7NFrB8dESuDKif53TTp/3/z7p604lo/mrJVr3maF",
	"aI2Lo2JC/JCmADwlSSBxb0oCAfl4t4wFQKKiOTvijsYdpr2fBB0Nv8BxT/IEVs7XWKzg3m+32K8cee8T",
	"IVWEJRH9pANlPWHBTBWbF2b75Ql2YPtpUsepEwgZ6scxeke8uyQWX4hUNkSwKeiGsVyUgt/3qdnWy4KG",
	"ZY+wxheokfSQkaRycc7kKUsi/3nRRQHG+KM+fE4vrs4rB1StdU+4UlvzTrqHIASZWVxcD4ey5tICKi1l",
	"J9gxYJUY4776eLRysJBEJmLiMd+iym/j8SUyEkhLOHjKeEgk7mEayaPXayXUDDPguDD869y41XEHvuI7",
	"UwocsSmSc0DaSEhLl1b8of/+8syduMPhxXAy/njpblp2+ctUi1fV4EgnKS78psHXTZwau79j/qIWaGZv",
	"lRO8B5+SqzhgxD+lEQno37AhFr7Qwy5pNGt2MBoJSSLPYudzEkJmYQFc0ZBc2AK7RmQiaWjlPLq/biy4",
	"gU8kdNIvN4NSYebiRDaYGsKUg5i/CMYydE+H7ui3Aq8duepEq3+fUeVyi5UrN3XeEyINWaAPH2X6/Xlh",
	"iXwfszBkUUvBd6Tgme0as+NEztmXZJgO9jTZ8CdEE4xdAtLZZXfqZOyrs17VsaSnkxmquFybucY0BJbI",
	"54780eXF+cidjAfv3YurcTWEK617il1tyuKGpmbcdOopkQPdsUgCaBgzbtgnUV6MZ1TOk9sDj4Xdmd72",
	"rh5bqX0V+216/ZWxbWz3glm/Sgn7AQfiL9wHKqR43ri6GrnDSf9s6PZPPk7cD4PRuFIDsAnsK7p0dtyE",
	"wl8DqcWUOl+CIdqVjLqS2K7Xa/pX89THBeJCSpuvwOY7f5CA+i+gMKn5UX88uDifnPYHZ1VCVW/ek8NU",
	"w3p33vNEwV1QcJ9uvdt6ntBhGwyg0xYv4VQuRmpIs+J3QDjwfqI0W+Jb/ek0W/d//1T8XSugw1O3rm0w",
	"lzIuJCH6WuOYsTsKJtnCPeyZj5mVMDei6VVDPhKJ6e+gkkYFE9GU1U86dXBymAKHNCWj0hTPyD1lCVcH",
	"qzp6gAsjf3hwePBKKcdiiEhMcQ8fHRweHOrClJzrtXcVueoKkzuZkiYzx1F5blOsQgRF8Bml4liPzHW8",
	"D/xcaJS3chMFOhlWnsUiCZEenMRxkF5hdP8SJkTMJm9zAWtddlX2ibTUyFMf18t6fXi4Nx1sV1hahbLN",
	"jEdm1kJ8DWv4zR61aQJdi0bphiiylHZBU0ID8E1JxWj26nH2aqtyNNJqIY+DrviQQKzV+mWPBtuqSVr9",
	"KEz+Zm+TW5MV61aZNl1DYYnMtClAGO5d3zhYJGFI+KI5RiWZCX3DWbo5xDdqqHL4d1NoaoaBFOZ0jchL",
	"OIdIZjMdoLxRX8lSgeBBcqLvYaechcgAoajBRrmAg58/cFMzNETu/uJjU+VqB7UKMbs//9xUobfoBFoc",
	"RUyiqerQRuyWiF1aqcL1zaoUyhvi7Msiepn+NaH+qsvhnt3BpuhW7Yg0HvBGYB2oMeEkBAlc6JVpuqPL",
	"BznZWU+Pqye0s6P9U9J384i4UL7psu6ttsw/9yjf9OzEol3ZM1uk+n6QqgBBNTDYiDuxyuN6SzwDW/pA",
	"In0RLxQXYBwRNAcSyLk3B++uBjOXpmj5aOFeuiGz2EctpRTjrYdsZ5/KqPq8UmmqWUPBZcx2p66SCH1i",
	"bM01lVxDknllmh4vwyy+jHni9LJUdrRsjjLLox1BW8q/TeoQ0wWB7pPe0D8Wb97bYXS058yi4amuTSct",
	"jyRTRmIJ90DhouncnkxbOXSxZHedlsQrFLqKIhkSGfApAFF3mb+4XXV9IJ6k90RuoMknuUwTRq0lUpza",
	"TpTXr36/Z56ssWBtQ78lyD8cJrUU/gcDShuc2cDyc3Z39I3ULb+DelT+Vrthf2ISV79ps+xibtK2otCS",
	"uBabNpC4zwXQyMCpAEhVhOou878NsdOQlVgQy7zHaUKsymudnZhceea90Ln9g2TDM6QWJFuQbFlli9zf",
	"jtw5rn4rcnfNa8xdSKeRbHyWkjb+IAhu+43rE8N35Z261an149wWuFvgboH7uW/06jiZ4XEGsTuDcXeZ",
	"vpHfkVw3IHPxhwTPgMxOw5OFfGUvmry30N9Cfwv9LfTvAv11IP5y6N9ya9/3/bSKovymzPvLqF//Tzo/",
	"Ditv/i9BTwzQu13VEd8Hv8XoFqNbjP5O6iqbYParyiu1NxAG2gOQYHshHLL7rFpuXvVvQnojrgDxlLPw",
	"OeHeeepHF2+eGMm5NnX6S4v1jrSI3l4ntuC5ftO8Bb7sCLpxJjOFtpPBsoQH6Q9De91uwDwSzJmQvbeH",
	"bw+7JKZYyafz2H7haYb6WaQvpFGOqGKNW+lrWoVq1X+GYH6gYOtUebVd76xw2trTMP96hxzQrb0KNrQp",
	"qqsDtn5ZRlLvZH5LjNLYsPbVTZv6SsbJrKGzadvQO6YxBDSyd88ahd7hh452007pWDAR3smjuiKjRF46",
	"AK2ciiNZ1/DCcH3l4IjJjqahVn1fHEnO/8GWRd1nPAFWDk5R2KrXizoc1sTDuuUvkxStVqv/BwAA//8e",
	"8swWEVoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
