//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/google/uuid"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes         = "BearerAuth.Scopes"
	RefreshTokenCookieScopes = "RefreshTokenCookie.Scopes"
)

// AccessForbiddenErrorResponse defines model for AccessForbiddenErrorResponse.
type AccessForbiddenErrorResponse struct {
	Error struct {
		Type interface{} `json:"type,omitempty"`
	} `json:"error"`
}

// AccessTokenResponse defines model for AccessTokenResponse.
type AccessTokenResponse struct {
	// AccessToken Short-lived token for accessing protected endpoints
	AccessToken string `json:"access_token"`
}

// AddUserToWorkspaceRequest defines model for AddUserToWorkspaceRequest.
type AddUserToWorkspaceRequest struct {
	UserUUID UUID `json:"user_uuid"`
}

// AuthenticationErrorResponse defines model for AuthenticationErrorResponse.
type AuthenticationErrorResponse = ErrorResponse

// CreateSecretRequest defines model for CreateSecretRequest.
type CreateSecretRequest = SecretRequestCommon

// CreateSessionErrorResponse defines model for CreateSessionErrorResponse.
type CreateSessionErrorResponse = ErrorResponse

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	IsAdmin  bool   `json:"is_admin,omitempty"`
	Password string `json:"password"`

	// Username Must be unique
	Username string `json:"username"`
}

// CreateWorkspaceRequest defines model for CreateWorkspaceRequest.
type CreateWorkspaceRequest = WorkspaceRequestCommon

// EmptyResponse defines model for EmptyResponse.
type EmptyResponse = empty

// EntityNotFoundErrorResponse defines model for EntityNotFoundErrorResponse.
type EntityNotFoundErrorResponse = ErrorResponse

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	ErrorBody struct {
		// Type Identifier of the error type
		Type string `json:"type"`

		// StatusCode HTTP status code
		StatusCode int32 `json:"status_code"`

		// Message Error message
		Message string `json:"message,omitempty"`
	} `json:"error"`
}

// MediaUploadFinalizeErrorResponse defines model for MediaUploadFinalizeErrorResponse.
type MediaUploadFinalizeErrorResponse = ErrorResponse

// PingResponse defines model for PingResponse.
type PingResponse struct {
	// Instance Name of the server instance
	Instance string `json:"instance"`

	// ServerTime Server time
	ServerTime time.Time `json:"server_time"`
}

// RefreshSessionErrorResponse defines model for RefreshSessionErrorResponse.
type RefreshSessionErrorResponse = ErrorResponse

// RoleRequiredErrorResponse defines model for RoleRequiredErrorResponse.
type RoleRequiredErrorResponse = ErrorResponse

// SecretRequestCommon defines model for SecretRequestCommon.
type SecretRequestCommon struct {
	Name string `json:"name"`

	// Value Secret value to store. It'll be encrypted and never displayed as is
	Value string `json:"value"`
}

// SecretResponse defines model for SecretResponse.
type SecretResponse struct {
	AuthorUUID UUID      `json:"author_uuid"`
	CreatedAt  time.Time `json:"created_at"`
	Name       string    `json:"name"`
	UUID       UUID      `json:"uuid"`
}

// TimeoutErrorResponse defines model for TimeoutErrorResponse.
type TimeoutErrorResponse = ErrorResponse

// UUID defines model for UUID.
type UUID = uuid.UUID

// UpdateSecretRequest defines model for UpdateSecretRequest.
type UpdateSecretRequest = SecretRequestCommon

// UpdateWorkspaceRequest defines model for UpdateWorkspaceRequest.
type UpdateWorkspaceRequest = WorkspaceRequestCommon

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt time.Time `json:"created_at"`
	IsAdmin   bool      `json:"is_admin"`
	Username  string    `json:"username"`
	UUID      UUID      `json:"uuid"`
}

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse = ErrorResponse

// WorkspaceRequestCommon defines model for WorkspaceRequestCommon.
type WorkspaceRequestCommon struct {
	Name string `json:"name"`
}

// WorkspaceResponse defines model for WorkspaceResponse.
type WorkspaceResponse struct {
	CreatedAt time.Time `json:"created_at"`
	Name      string    `json:"name"`
	UUID      UUID      `json:"uuid"`
}

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// CreateWorkspaceJSONRequestBody defines body for CreateWorkspace for application/json ContentType.
type CreateWorkspaceJSONRequestBody = CreateWorkspaceRequest

// UpdateWorkspaceJSONRequestBody defines body for UpdateWorkspace for application/json ContentType.
type UpdateWorkspaceJSONRequestBody = UpdateWorkspaceRequest

// CreateSecretJSONRequestBody defines body for CreateSecret for application/json ContentType.
type CreateSecretJSONRequestBody = CreateSecretRequest

// UpdateSecretJSONRequestBody defines body for UpdateSecret for application/json ContentType.
type UpdateSecretJSONRequestBody = UpdateSecretRequest

// AddUserToWorkspaceJSONRequestBody defines body for AddUserToWorkspace for application/json ContentType.
type AddUserToWorkspaceJSONRequestBody = AddUserToWorkspaceRequest

type CreateSessionRequestObject struct {
	Body *CreateSessionJSONRequestBody
}

type CreateSessionResponseObject interface {
	VisitCreateSessionResponse(w http.ResponseWriter) error
}

func (r AccessTokenResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type RefreshSessionRequestObject struct {
}

type RefreshSessionResponseObject interface {
	VisitRefreshSessionResponse(w http.ResponseWriter) error
}

func (r AccessTokenResponse) VisitRefreshSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type RevokeSessionRequestObject struct {
	SessionID UUID `json:"session_id"`
}

type RevokeSessionResponseObject interface {
	VisitRevokeSessionResponse(w http.ResponseWriter) error
}

func (r EmptyResponse) VisitRevokeSessionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type PingRequestObject struct {
}

type PingResponseObject interface {
	VisitPingResponse(w http.ResponseWriter) error
}

func (r PingResponse) VisitPingResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

func (r UserResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type DeactivateUserRequestObject struct {
	UserUUID UUID `json:"user_uuid"`
}

type DeactivateUserResponseObject interface {
	VisitDeactivateUserResponse(w http.ResponseWriter) error
}

func (r EmptyResponse) VisitDeactivateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type CreateWorkspaceRequestObject struct {
	Body *CreateWorkspaceJSONRequestBody
}

type CreateWorkspaceResponseObject interface {
	VisitCreateWorkspaceResponse(w http.ResponseWriter) error
}

func (r WorkspaceResponse) VisitCreateWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type UpdateWorkspaceRequestObject struct {
	WorkspaceUUID UUID `json:"workspace_uuid"`
	Body          *UpdateWorkspaceJSONRequestBody
}

type UpdateWorkspaceResponseObject interface {
	VisitUpdateWorkspaceResponse(w http.ResponseWriter) error
}

func (r WorkspaceResponse) VisitUpdateWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type CreateSecretRequestObject struct {
	WorkspaceUUID UUID `json:"workspace_uuid"`
	Body          *CreateSecretJSONRequestBody
}

type CreateSecretResponseObject interface {
	VisitCreateSecretResponse(w http.ResponseWriter) error
}

func (r SecretResponse) VisitCreateSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type UpdateSecretRequestObject struct {
	WorkspaceUUID UUID `json:"workspace_uuid"`
	SecretUUID    UUID `json:"secret_uuid"`
	Body          *UpdateSecretJSONRequestBody
}

type UpdateSecretResponseObject interface {
	VisitUpdateSecretResponse(w http.ResponseWriter) error
}

func (r SecretResponse) VisitUpdateSecretResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type AddUserToWorkspaceRequestObject struct {
	WorkspaceUUID UUID `json:"workspace_uuid"`
	Body          *AddUserToWorkspaceJSONRequestBody
}

type AddUserToWorkspaceResponseObject interface {
	VisitAddUserToWorkspaceResponse(w http.ResponseWriter) error
}

func (r EmptyResponse) VisitAddUserToWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(r)
}

type RemoveUserFromWorkspaceRequestObject struct {
	WorkspaceUUID UUID `json:"workspace_uuid"`
	UserUUID      UUID `json:"user_uuid"`
}

type RemoveUserFromWorkspaceResponseObject interface {
	VisitRemoveUserFromWorkspaceResponse(w http.ResponseWriter) error
}

func (r EmptyResponse) VisitRemoveUserFromWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(204)

	return json.NewEncoder(w).Encode(r)
}

// HandlerInterface represents all server handlers.
type HandlerInterface interface {
	// Create a new session
	// (POST /auth/sessions)
	CreateSession(w http.ResponseWriter, r *http.Request, request CreateSessionRequestObject) (CreateSessionResponseObject, error)
	// Refresh the current session
	// (POST /auth/sessions/refresh)
	RefreshSession(w http.ResponseWriter, r *http.Request, request RefreshSessionRequestObject) (RefreshSessionResponseObject, error)
	// Revoke a session
	// (POST /auth/sessions/{session_id}/revoke)
	RevokeSession(w http.ResponseWriter, r *http.Request, request RevokeSessionRequestObject) (RevokeSessionResponseObject, error)
	// Ping the API server
	// (GET /ping)
	Ping(w http.ResponseWriter, r *http.Request, request PingRequestObject) (PingResponseObject, error)
	// Create a user
	// (POST /users)
	CreateUser(w http.ResponseWriter, r *http.Request, request CreateUserRequestObject) (CreateUserResponseObject, error)
	// Deactivate a user
	// (POST /users/{user_uuid}/deactivate)
	DeactivateUser(w http.ResponseWriter, r *http.Request, request DeactivateUserRequestObject) (DeactivateUserResponseObject, error)
	// Create a workspace
	// (POST /workspaces)
	CreateWorkspace(w http.ResponseWriter, r *http.Request, request CreateWorkspaceRequestObject) (CreateWorkspaceResponseObject, error)
	// Update a workspace
	// (PUT /workspaces/{workspace_uuid})
	UpdateWorkspace(w http.ResponseWriter, r *http.Request, request UpdateWorkspaceRequestObject) (UpdateWorkspaceResponseObject, error)
	// Create a secret
	// (POST /workspaces/{workspace_uuid}/secrets)
	CreateSecret(w http.ResponseWriter, r *http.Request, request CreateSecretRequestObject) (CreateSecretResponseObject, error)
	// Update a secret
	// (PUT /workspaces/{workspace_uuid}/secrets/{secret_uuid})
	UpdateSecret(w http.ResponseWriter, r *http.Request, request UpdateSecretRequestObject) (UpdateSecretResponseObject, error)
	// Add a user to a workspace
	// (POST /workspaces/{workspace_uuid}/users)
	AddUserToWorkspace(w http.ResponseWriter, r *http.Request, request AddUserToWorkspaceRequestObject) (AddUserToWorkspaceResponseObject, error)
	// Remove a user from a workspace
	// (DELETE /workspaces/{workspace_uuid}/users/{user_uuid})
	RemoveUserFromWorkspace(w http.ResponseWriter, r *http.Request, request RemoveUserFromWorkspaceRequestObject) (RemoveUserFromWorkspaceResponseObject, error)
}

// HandlerInterfaceWrapper converts contexts to parameters.
type HandlerInterfaceWrapper struct {
	handler HandlerInterface
	options Options
}

// CreateSession operation middleware
func (hiw *HandlerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	var request CreateSessionRequestObject

	var body CreateSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	response, err := hiw.handler.CreateSession(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitCreateSessionResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// RefreshSession operation middleware
func (hiw *HandlerInterfaceWrapper) RefreshSession(w http.ResponseWriter, r *http.Request) {

	var request RefreshSessionRequestObject

	response, err := hiw.handler.RefreshSession(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitRefreshSessionResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// RevokeSession operation middleware
func (hiw *HandlerInterfaceWrapper) RevokeSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "session_id" -------------
	var sessionID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "session_id", r.PathValue("session_id"), &sessionID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "session_id", Err: err})
		return
	}

	var request RevokeSessionRequestObject

	request.SessionID = sessionID

	response, err := hiw.handler.RevokeSession(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitRevokeSessionResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// Ping operation middleware
func (hiw *HandlerInterfaceWrapper) Ping(w http.ResponseWriter, r *http.Request) {

	var request PingRequestObject

	response, err := hiw.handler.Ping(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitPingResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// CreateUser operation middleware
func (hiw *HandlerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	response, err := hiw.handler.CreateUser(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitCreateUserResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// DeactivateUser operation middleware
func (hiw *HandlerInterfaceWrapper) DeactivateUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_uuid" -------------
	var userUUID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "user_uuid", r.PathValue("user_uuid"), &userUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_uuid", Err: err})
		return
	}

	var request DeactivateUserRequestObject

	request.UserUUID = userUUID

	response, err := hiw.handler.DeactivateUser(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitDeactivateUserResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// CreateWorkspace operation middleware
func (hiw *HandlerInterfaceWrapper) CreateWorkspace(w http.ResponseWriter, r *http.Request) {

	var request CreateWorkspaceRequestObject

	var body CreateWorkspaceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	response, err := hiw.handler.CreateWorkspace(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitCreateWorkspaceResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// UpdateWorkspace operation middleware
func (hiw *HandlerInterfaceWrapper) UpdateWorkspace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspace_uuid" -------------
	var workspaceUUID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "workspace_uuid", r.PathValue("workspace_uuid"), &workspaceUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_uuid", Err: err})
		return
	}

	var request UpdateWorkspaceRequestObject

	request.WorkspaceUUID = workspaceUUID

	var body UpdateWorkspaceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	response, err := hiw.handler.UpdateWorkspace(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitUpdateWorkspaceResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// CreateSecret operation middleware
func (hiw *HandlerInterfaceWrapper) CreateSecret(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspace_uuid" -------------
	var workspaceUUID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "workspace_uuid", r.PathValue("workspace_uuid"), &workspaceUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_uuid", Err: err})
		return
	}

	var request CreateSecretRequestObject

	request.WorkspaceUUID = workspaceUUID

	var body CreateSecretJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	response, err := hiw.handler.CreateSecret(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitCreateSecretResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// UpdateSecret operation middleware
func (hiw *HandlerInterfaceWrapper) UpdateSecret(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspace_uuid" -------------
	var workspaceUUID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "workspace_uuid", r.PathValue("workspace_uuid"), &workspaceUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_uuid", Err: err})
		return
	}

	// ------------- Path parameter "secret_uuid" -------------
	var secretUUID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "secret_uuid", r.PathValue("secret_uuid"), &secretUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "secret_uuid", Err: err})
		return
	}

	var request UpdateSecretRequestObject

	request.WorkspaceUUID = workspaceUUID
	request.SecretUUID = secretUUID

	var body UpdateSecretJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	response, err := hiw.handler.UpdateSecret(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitUpdateSecretResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// AddUserToWorkspace operation middleware
func (hiw *HandlerInterfaceWrapper) AddUserToWorkspace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspace_uuid" -------------
	var workspaceUUID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "workspace_uuid", r.PathValue("workspace_uuid"), &workspaceUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_uuid", Err: err})
		return
	}

	var request AddUserToWorkspaceRequestObject

	request.WorkspaceUUID = workspaceUUID

	var body AddUserToWorkspaceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	response, err := hiw.handler.AddUserToWorkspace(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitAddUserToWorkspaceResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

// RemoveUserFromWorkspace operation middleware
func (hiw *HandlerInterfaceWrapper) RemoveUserFromWorkspace(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "workspace_uuid" -------------
	var workspaceUUID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "workspace_uuid", r.PathValue("workspace_uuid"), &workspaceUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "workspace_uuid", Err: err})
		return
	}

	// ------------- Path parameter "user_uuid" -------------
	var userUUID UUID

	err = runtime.BindStyledParameterWithOptions("simple", "user_uuid", r.PathValue("user_uuid"), &userUUID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		hiw.options.RequestErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_uuid", Err: err})
		return
	}

	var request RemoveUserFromWorkspaceRequestObject

	request.WorkspaceUUID = workspaceUUID
	request.UserUUID = userUUID

	response, err := hiw.handler.RemoveUserFromWorkspace(w, r, request)

	if err != nil {
		hiw.options.ResponseErrorHandlerFunc(w, r, err)
		return
	}

	if response != nil {
		if err := response.VisitRemoveUserFromWorkspaceResponse(w); err != nil {
			hiw.options.ResponseErrorHandlerFunc(w, r, err)
		}
	}
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(hi HandlerInterface) http.Handler {
	return HandlerWithOptions(hi, Options{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type Options struct {
	BaseURL                  string
	BaseRouter               ServeMux
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

const (
	CreateSessionPath           = "/auth/sessions"
	RefreshSessionPath          = "/auth/sessions/refresh"
	RevokeSessionPath           = "/auth/sessions/{session_id}/revoke"
	PingPath                    = "/ping"
	CreateUserPath              = "/users"
	DeactivateUserPath          = "/users/{user_uuid}/deactivate"
	CreateWorkspacePath         = "/workspaces"
	UpdateWorkspacePath         = "/workspaces/{workspace_uuid}"
	CreateSecretPath            = "/workspaces/{workspace_uuid}/secrets"
	UpdateSecretPath            = "/workspaces/{workspace_uuid}/secrets/{secret_uuid}"
	AddUserToWorkspacePath      = "/workspaces/{workspace_uuid}/users"
	RemoveUserFromWorkspacePath = "/workspaces/{workspace_uuid}/users/{user_uuid}"
)

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(hi HandlerInterface, options Options) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}

	wrapper := HandlerInterfaceWrapper{
		handler: hi,
		options: options,
	}

	m.HandleFunc("POST "+options.BaseURL+CreateSessionPath, wrapper.CreateSession)
	m.HandleFunc("POST "+options.BaseURL+RefreshSessionPath, wrapper.RefreshSession)
	m.HandleFunc("POST "+options.BaseURL+RevokeSessionPath, wrapper.RevokeSession)
	m.HandleFunc("GET "+options.BaseURL+PingPath, wrapper.Ping)
	m.HandleFunc("POST "+options.BaseURL+CreateUserPath, wrapper.CreateUser)
	m.HandleFunc("POST "+options.BaseURL+DeactivateUserPath, wrapper.DeactivateUser)
	m.HandleFunc("POST "+options.BaseURL+CreateWorkspacePath, wrapper.CreateWorkspace)
	m.HandleFunc("PUT "+options.BaseURL+UpdateWorkspacePath, wrapper.UpdateWorkspace)
	m.HandleFunc("POST "+options.BaseURL+CreateSecretPath, wrapper.CreateSecret)
	m.HandleFunc("PUT "+options.BaseURL+UpdateSecretPath, wrapper.UpdateSecret)
	m.HandleFunc("POST "+options.BaseURL+AddUserToWorkspacePath, wrapper.AddUserToWorkspace)
	m.HandleFunc("DELETE "+options.BaseURL+RemoveUserFromWorkspacePath, wrapper.RemoveUserFromWorkspace)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcbXPiOBL+KyrdVu2HMyEzmd2a4huTkFtuZ0gKyL5UKkcpdgPa2JZHkjNhKf77lSTb",
	"+EUGkiEJM+tv2GpJrVb3o0ctmSV2WRCxEEIpcGeJhTuHgOifXdcFIc4Zv6WeB2GPc8aHICIWClDlxPcv",
	"prhzvcQ/cJjiDv5Xe91WO2moXay2cpY44iwCLinoXkCVqx/F13IR6U4gjAPcucbd09PeaDQ5vxh+6J+d",
	"9Qb4xsHwQILIB9yplq5Wq5WTNILZ7V/gSry6WTnJoMbsDsL8WIqdEy00kUpKPXsgXE4jSVmIO3g0Z1y2",
	"fHoPHtIiaMo4MnVoOEMRZxJcCR6C0IsYVZbNdBGS03CGlXYcPseUg6eGV+jxpqK5g7uedyWAj9nvjN+J",
	"iLgwhM8xCFnVPhbAJ3FMPfWwaWqurvpnFU3Wta1qxHIOoaQuUcY4CJcYX/zaG0wGF+PJb92P/TPsFAt6",
	"f1z2h70zq7+Uq1q9xlmW3jj4oTVjreRlaTDKx045EAkjcDnI2lkKSWBGkyn1H8ZmPqDuZR/dwQI7OCAP",
	"HyGcyTnu/PzOwQEN08d3FX9y8D3xY7B4q1YD6VIkGRKScThCffmj76NbQBC6fBEpbyWhh0K4B448KiKf",
	"LNQ7gajy3rWWwWIidJMT02FBrzfb/FyPOtXV5mCp7YR4df/qD7RXTE6HvbPeYNzvfhwVvcgmsGcX0mao",
	"9aGICPGFca/oR6P4Z+AjcIcn46oTVdxGxXvqiznZk7cOjoiUwJUT/e+atP6++fcPW3Esa81ZK1c/zQrR",
	"agdHxYR4AU0AeEpiX+LOlPgCsvZuGfOBhHlztsQdjVpMez/xWxp+geOO5DGsnKdYLOfe77fYrxh5n2Ih",
	"VYTFIf2sA2XdYc5MJZvnevvpBWZg+2pSxakzCBjqRhH6QNy7OBKPRCobItgU7AWRXBSC3/OomdbLnIZF",
	"j7DGF6iWdJOhpHIxYPKcxaH3uuiiAGP8p158zi+uBqUFqlK6J1ypjHkn3QMQgswsLq6bQ2lxYQClkqIT",
	"7BiwSoxxTz2erBwsJJGxmLjMs6jyy3h8iYwE0hIOnjIeEIk7mIby5O1aCdXDDDjONf82M2653b6n+M6U",
	"AkdsiuQckDYS0tKFEf/R/XT5sTfpDYcXw8n4z8vepmEXXyZavCkHR9JJfuA3Nb5u4tTY/QPzFpVAM3Or",
	"nOATeJRcRT4j3jkNiU//hg2x8EgPu6ThrN7BaCgkCV2LnQckgNTCAriiIZmwBXaNyETSwMp5dH1dmHMD",
	"j0hoJS83g1Ku53xHNpgawpSDmB8EYxn2zoe90S85XjvqqRWt+j6lysUSK1euq7wnRBoyXy8+yvT788IC",
	"+T5lQcDChoLvSMFT29XujmM5Z4/ZYTrY1WTDmxBNMHYJSGeX2amSsSfvelXFgp5Oaqj8cG3mGtMAWCxf",
	"O/JHlxeDUW8y7n/qXVyNyyFcKt1T7GpT5ic0MeOmVU+JHOmKeRJAg4hxwz6J8mI8o3Ie3x65LGjP9LS3",
	"ddtK7avIa7bXT4xtY7sDZv1mS1gHPU/Bkfw+MhuOYZelbWRpN7ceu6lf3pw9L/rk9nHZCGwG+4341DuA",
	"bJwmBd1x/2IwOe/2P5ZZRLV4TxhU9uXdF/sX8uicgvt0693G84IOW2MAzdXdmFO5GKkmzYg/AOHAu7HS",
	"bIlv9dN5Ou7//q5Iq1ZAh6cuXdtgLmWUY946l3/K2B0Fs8PAHeyax9RKmBvRJL+etUQi+iuonZKCiXDK",
	"qvCuVgsOU+CQ7EOoNBkjck9ZzNVqovAWuDDyx0fHR2+UciyCkEQUd/DJ0fHRsc7GyLkee1sxirYwGwaT",
	"x2MGg4t9mwwNIiiELygRx7plruO972VCo6yUmyjQO0DlWSyUEOrGSRT5Sd6+/ZcwIWImeZsLWJORq6JP",
	"JPk1nvi4Htbb4+O96WA7t9EqFG1mPDK1FuJrWMPv9qhNHehaNEomRDGEpAqaEuqDZ/IIRrM3zzNXW5Wj",
	"oVYLuRx0moP4Yq3WT3s02FZNki1/rvN3e+vcytCtU2XKdOKAxTLVJgdhuHN942ARBwHhi/oYlWQm9LFe",
	"4bgM36imiuHfTqCpHgYSmNOJETfmHEKZ9nSEskJ9DkkFggfJiT58nHIWIAOEogIbxawFfv3ATcxQE7n7",
	"i49N6Zod1MrF7P78c1Na2qITaHEUMommqkITsVsidmmlCtc3q0Iob4izx0X0Mvk1od6qzeGe3cGm6Fbl",
	"iNQu8EZgHagR4SQACVzokWm6o/fMGdlZd4/LK7Szo/0T0nfzjLhQPN6xzq22zD93Kd9018KiXdEzG6T6",
	"dpAqB0EVMNiIO5Hax3WWeAa27QMJ9emzUFyAcUTQHIgv5+4c3LsKzFyaTN2zhXvhWMhiHzWUQow3HrKd",
	"fSqj6vVKbVPNGHIuY6Y7cZVY6BVj615TydVsMq9M0fPtMPPXQV54e1lIO1omR5mlWYKevgSd7Hk/UXMr",
	"1aaTlkeSqeljMXdBoaGp3KxHW5lzPlF3nSTCS8S5jB0p/hjIycFPe5ldLl21PSCupPdEbiDHZ5lMHTKt",
	"JRJ02k6P1xdcv2V2rAFpbUOvwaTvDpMa4v6dAaUNzmxg+SU9MfpKwpadPD0ra6scJr8wdauer1lmMTNp",
	"Q+IaEtdg0wYS9yUHGik45QCpjFDtZfbbEDsNWbEFsczVkzrEKl1M2YnJFXveC53bP0jW3LhpQLIByYZV",
	"Nsj99cid4erXInfbXDzchXQaydrLKEnhd4Lgts85Xxi+S1eyrU6t76E2wN0AdwPcr32OV8XJFI9TiN0Z",
	"jNvL5Dr4juS6Bpnzd+ZfAZmdmosK2cgOmrw30N9AfwP9DfTvAv1VIH489G85q+96XpJFUX5T5P1F1K/+",
	"acz3w8rr/xDnhQF6t6M64nngNRjdYHSD0d9IXmUTzD4pvVK5A2Gg3QcJtnvBAbtPs+XmLv8mpDfiChDP",
	"OQteE+6dl7508e6FkZxrUyffV6xnpEH05jixAc/1TeYt8GVH0I09mS60nQyWxdxPPgfttNs+c4k/Z0J2",
	"3h+/P26TiGIln/Rj+67TNPWjSO5FowxRxRq3kju0CtXK3/2bzxJslUp3tauVFU5baxrmX62QAbq1Vs6G",
	"NkV1dsBWL92RVCuZL4hREhvWurpoU13JOJnVVDZlG2pHNAKfhvbqaaHQM/zQ0m7aKiwLJsJbWVSXZJTI",
	"oQPQyik5knUMB4brKweHTLY0DbXqe3AkOfsvKYu6r7gCrBycoLBVr4NaHNbEwzrlh0mKVqvV/wMAAP//",
	"dJhdAvxYAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
