# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/Overlay-Specification/refs/heads/main/schemas/v1.0/schema.yaml
overlay: 1.0.0
info:
  title: "Schema adjustments for better go code generation. Overlay reference: https://spec.openapis.org/overlay/v1.0.0.html"
  description:
  version: 0.1.0
actions:
  - target: "$.components.schemas"
    description: "Fine tune go structs. See https://github.com/oapi-codegen/oapi-codegen?tab=readme-ov-file#openapi-extensions"
    update:
      ErrorResponse:
        properties:
          error:
            x-go-name: ErrorBody
            properties:
              type:
                x-order: 1
                x-go-type: string
              status_code:
                x-order: 2
              message:
                x-order: 3
                x-go-type-skip-optional-pointer: true
      EntityNotFoundErrorResponse:
        allOf:
          - type: object
            x-go-type: ErrorResponse
      ValidationErrorResponse:
        allOf:
          - type: object
            x-go-type: ErrorResponse
      TimeoutErrorResponse:
        allOf:
          - type: object
            x-go-type: ErrorResponse
