// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testmock

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"saviour/internal/model"
	"saviour/internal/service/auth"
)

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the Service type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockAuthService
func (_mock *MockAuthService) CreateSession(ctx context.Context, params auth.CreateSessionParams) (*model.TokenPair, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *model.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.CreateSessionParams) (*model.TokenPair, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.CreateSessionParams) *model.TokenPair); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.CreateSessionParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockAuthService_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - params auth.CreateSessionParams
func (_e *MockAuthService_Expecter) CreateSession(ctx interface{}, params interface{}) *MockAuthService_CreateSession_Call {
	return &MockAuthService_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, params)}
}

func (_c *MockAuthService_CreateSession_Call) Run(run func(ctx context.Context, params auth.CreateSessionParams)) *MockAuthService_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.CreateSessionParams
		if args[1] != nil {
			arg1 = args[1].(auth.CreateSessionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_CreateSession_Call) Return(tokenPair *model.TokenPair, err error) *MockAuthService_CreateSession_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockAuthService_CreateSession_Call) RunAndReturn(run func(ctx context.Context, params auth.CreateSessionParams) (*model.TokenPair, error)) *MockAuthService_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshSession provides a mock function for the type MockAuthService
func (_mock *MockAuthService) RefreshSession(ctx context.Context, params auth.RefreshSessionParams) (*model.TokenPair, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RefreshSession")
	}

	var r0 *model.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.RefreshSessionParams) (*model.TokenPair, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.RefreshSessionParams) *model.TokenPair); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, auth.RefreshSessionParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_RefreshSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshSession'
type MockAuthService_RefreshSession_Call struct {
	*mock.Call
}

// RefreshSession is a helper method to define mock.On call
//   - ctx context.Context
//   - params auth.RefreshSessionParams
func (_e *MockAuthService_Expecter) RefreshSession(ctx interface{}, params interface{}) *MockAuthService_RefreshSession_Call {
	return &MockAuthService_RefreshSession_Call{Call: _e.mock.On("RefreshSession", ctx, params)}
}

func (_c *MockAuthService_RefreshSession_Call) Run(run func(ctx context.Context, params auth.RefreshSessionParams)) *MockAuthService_RefreshSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.RefreshSessionParams
		if args[1] != nil {
			arg1 = args[1].(auth.RefreshSessionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_RefreshSession_Call) Return(tokenPair *model.TokenPair, err error) *MockAuthService_RefreshSession_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockAuthService_RefreshSession_Call) RunAndReturn(run func(ctx context.Context, params auth.RefreshSessionParams) (*model.TokenPair, error)) *MockAuthService_RefreshSession_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function for the type MockAuthService
func (_mock *MockAuthService) RevokeSession(ctx context.Context, params auth.RevokeSessionParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, auth.RevokeSessionParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuthService_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type MockAuthService_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - params auth.RevokeSessionParams
func (_e *MockAuthService_Expecter) RevokeSession(ctx interface{}, params interface{}) *MockAuthService_RevokeSession_Call {
	return &MockAuthService_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, params)}
}

func (_c *MockAuthService_RevokeSession_Call) Run(run func(ctx context.Context, params auth.RevokeSessionParams)) *MockAuthService_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 auth.RevokeSessionParams
		if args[1] != nil {
			arg1 = args[1].(auth.RevokeSessionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_RevokeSession_Call) Return(err error) *MockAuthService_RevokeSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuthService_RevokeSession_Call) RunAndReturn(run func(ctx context.Context, params auth.RevokeSessionParams) error) *MockAuthService_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}
