// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testmock

import (
	"context"
	"database/sql"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDB creates a new instance of MockDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDB {
	mock := &MockDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDB is an autogenerated mock type for the DBTX type
type MockDB struct {
	mock.Mock
}

type MockDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDB) EXPECT() *MockDB_Expecter {
	return &MockDB_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function for the type MockDB
func (_mock *MockDB) BeginTx(ctx context.Context, opts *sql.TxOptions) (*sql.Tx, error) {
	ret := _mock.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 *sql.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) (*sql.Tx, error)); ok {
		return returnFunc(ctx, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) *sql.Tx); ok {
		r0 = returnFunc(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sql.TxOptions) error); ok {
		r1 = returnFunc(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDB_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockDB_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *sql.TxOptions
func (_e *MockDB_Expecter) BeginTx(ctx interface{}, opts interface{}) *MockDB_BeginTx_Call {
	return &MockDB_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, opts)}
}

func (_c *MockDB_BeginTx_Call) Run(run func(ctx context.Context, opts *sql.TxOptions)) *MockDB_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sql.TxOptions
		if args[1] != nil {
			arg1 = args[1].(*sql.TxOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDB_BeginTx_Call) Return(tx *sql.Tx, err error) *MockDB_BeginTx_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *MockDB_BeginTx_Call) RunAndReturn(run func(ctx context.Context, opts *sql.TxOptions) (*sql.Tx, error)) *MockDB_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// ExecContext provides a mock function for the type MockDB
func (_mock *MockDB) ExecContext(context1 context.Context, s string, ifaceVals ...interface{}) (sql.Result, error) {
	var tmpRet mock.Arguments
	if len(ifaceVals) > 0 {
		tmpRet = _mock.Called(context1, s, ifaceVals)
	} else {
		tmpRet = _mock.Called(context1, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 sql.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (sql.Result, error)); ok {
		return returnFunc(context1, s, ifaceVals...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) sql.Result); ok {
		r0 = returnFunc(context1, s, ifaceVals...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = returnFunc(context1, s, ifaceVals...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDB_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type MockDB_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - ifaceVals ...interface{}
func (_e *MockDB_Expecter) ExecContext(context1 interface{}, s interface{}, ifaceVals ...interface{}) *MockDB_ExecContext_Call {
	return &MockDB_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{context1, s}, ifaceVals...)...)}
}

func (_c *MockDB_ExecContext_Call) Run(run func(context1 context.Context, s string, ifaceVals ...interface{})) *MockDB_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []interface{}
		var variadicArgs []interface{}
		if len(args) > 2 {
			variadicArgs = args[2].([]interface{})
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDB_ExecContext_Call) Return(result sql.Result, err error) *MockDB_ExecContext_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockDB_ExecContext_Call) RunAndReturn(run func(context1 context.Context, s string, ifaceVals ...interface{}) (sql.Result, error)) *MockDB_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// PrepareContext provides a mock function for the type MockDB
func (_mock *MockDB) PrepareContext(context1 context.Context, s string) (*sql.Stmt, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for PrepareContext")
	}

	var r0 *sql.Stmt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*sql.Stmt, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *sql.Stmt); ok {
		r0 = returnFunc(context1, s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Stmt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDB_PrepareContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrepareContext'
type MockDB_PrepareContext_Call struct {
	*mock.Call
}

// PrepareContext is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockDB_Expecter) PrepareContext(context1 interface{}, s interface{}) *MockDB_PrepareContext_Call {
	return &MockDB_PrepareContext_Call{Call: _e.mock.On("PrepareContext", context1, s)}
}

func (_c *MockDB_PrepareContext_Call) Run(run func(context1 context.Context, s string)) *MockDB_PrepareContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDB_PrepareContext_Call) Return(stmt *sql.Stmt, err error) *MockDB_PrepareContext_Call {
	_c.Call.Return(stmt, err)
	return _c
}

func (_c *MockDB_PrepareContext_Call) RunAndReturn(run func(context1 context.Context, s string) (*sql.Stmt, error)) *MockDB_PrepareContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function for the type MockDB
func (_mock *MockDB) QueryContext(context1 context.Context, s string, ifaceVals ...interface{}) (*sql.Rows, error) {
	var tmpRet mock.Arguments
	if len(ifaceVals) > 0 {
		tmpRet = _mock.Called(context1, s, ifaceVals)
	} else {
		tmpRet = _mock.Called(context1, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 *sql.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) (*sql.Rows, error)); ok {
		return returnFunc(context1, s, ifaceVals...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) *sql.Rows); ok {
		r0 = returnFunc(context1, s, ifaceVals...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = returnFunc(context1, s, ifaceVals...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDB_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type MockDB_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - ifaceVals ...interface{}
func (_e *MockDB_Expecter) QueryContext(context1 interface{}, s interface{}, ifaceVals ...interface{}) *MockDB_QueryContext_Call {
	return &MockDB_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]interface{}{context1, s}, ifaceVals...)...)}
}

func (_c *MockDB_QueryContext_Call) Run(run func(context1 context.Context, s string, ifaceVals ...interface{})) *MockDB_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []interface{}
		var variadicArgs []interface{}
		if len(args) > 2 {
			variadicArgs = args[2].([]interface{})
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDB_QueryContext_Call) Return(rows *sql.Rows, err error) *MockDB_QueryContext_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockDB_QueryContext_Call) RunAndReturn(run func(context1 context.Context, s string, ifaceVals ...interface{}) (*sql.Rows, error)) *MockDB_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRowContext provides a mock function for the type MockDB
func (_mock *MockDB) QueryRowContext(context1 context.Context, s string, ifaceVals ...interface{}) *sql.Row {
	var tmpRet mock.Arguments
	if len(ifaceVals) > 0 {
		tmpRet = _mock.Called(context1, s, ifaceVals)
	} else {
		tmpRet = _mock.Called(context1, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRowContext")
	}

	var r0 *sql.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...interface{}) *sql.Row); ok {
		r0 = returnFunc(context1, s, ifaceVals...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.Row)
		}
	}
	return r0
}

// MockDB_QueryRowContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRowContext'
type MockDB_QueryRowContext_Call struct {
	*mock.Call
}

// QueryRowContext is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - ifaceVals ...interface{}
func (_e *MockDB_Expecter) QueryRowContext(context1 interface{}, s interface{}, ifaceVals ...interface{}) *MockDB_QueryRowContext_Call {
	return &MockDB_QueryRowContext_Call{Call: _e.mock.On("QueryRowContext",
		append([]interface{}{context1, s}, ifaceVals...)...)}
}

func (_c *MockDB_QueryRowContext_Call) Run(run func(context1 context.Context, s string, ifaceVals ...interface{})) *MockDB_QueryRowContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []interface{}
		var variadicArgs []interface{}
		if len(args) > 2 {
			variadicArgs = args[2].([]interface{})
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockDB_QueryRowContext_Call) Return(row *sql.Row) *MockDB_QueryRowContext_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *MockDB_QueryRowContext_Call) RunAndReturn(run func(context1 context.Context, s string, ifaceVals ...interface{}) *sql.Row) *MockDB_QueryRowContext_Call {
	_c.Call.Return(run)
	return _c
}
