// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testmock

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	"saviour/internal/model"
	"saviour/internal/repository"
)

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// CreateSession provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) CreateSession(ctx context.Context, params repository.CreateSessionParams) (*model.Session, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *model.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CreateSessionParams) (*model.Session, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CreateSessionParams) *model.Session); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.CreateSessionParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockSessionRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - params repository.CreateSessionParams
func (_e *MockSessionRepository_Expecter) CreateSession(ctx interface{}, params interface{}) *MockSessionRepository_CreateSession_Call {
	return &MockSessionRepository_CreateSession_Call{Call: _e.mock.On("CreateSession", ctx, params)}
}

func (_c *MockSessionRepository_CreateSession_Call) Run(run func(ctx context.Context, params repository.CreateSessionParams)) *MockSessionRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.CreateSessionParams
		if args[1] != nil {
			arg1 = args[1].(repository.CreateSessionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_CreateSession_Call) Return(session *model.Session, err error) *MockSessionRepository_CreateSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepository_CreateSession_Call) RunAndReturn(run func(ctx context.Context, params repository.CreateSessionParams) (*model.Session, error)) *MockSessionRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshActiveSession provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) RefreshActiveSession(ctx context.Context, params repository.RefreshActiveSessionParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RefreshActiveSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.RefreshActiveSessionParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_RefreshActiveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshActiveSession'
type MockSessionRepository_RefreshActiveSession_Call struct {
	*mock.Call
}

// RefreshActiveSession is a helper method to define mock.On call
//   - ctx context.Context
//   - params repository.RefreshActiveSessionParams
func (_e *MockSessionRepository_Expecter) RefreshActiveSession(ctx interface{}, params interface{}) *MockSessionRepository_RefreshActiveSession_Call {
	return &MockSessionRepository_RefreshActiveSession_Call{Call: _e.mock.On("RefreshActiveSession", ctx, params)}
}

func (_c *MockSessionRepository_RefreshActiveSession_Call) Run(run func(ctx context.Context, params repository.RefreshActiveSessionParams)) *MockSessionRepository_RefreshActiveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.RefreshActiveSessionParams
		if args[1] != nil {
			arg1 = args[1].(repository.RefreshActiveSessionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_RefreshActiveSession_Call) Return(err error) *MockSessionRepository_RefreshActiveSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_RefreshActiveSession_Call) RunAndReturn(run func(ctx context.Context, params repository.RefreshActiveSessionParams) error) *MockSessionRepository_RefreshActiveSession_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeSession provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) RevokeSession(ctx context.Context, params repository.RevokeSessionParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RevokeSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.RevokeSessionParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_RevokeSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeSession'
type MockSessionRepository_RevokeSession_Call struct {
	*mock.Call
}

// RevokeSession is a helper method to define mock.On call
//   - ctx context.Context
//   - params repository.RevokeSessionParams
func (_e *MockSessionRepository_Expecter) RevokeSession(ctx interface{}, params interface{}) *MockSessionRepository_RevokeSession_Call {
	return &MockSessionRepository_RevokeSession_Call{Call: _e.mock.On("RevokeSession", ctx, params)}
}

func (_c *MockSessionRepository_RevokeSession_Call) Run(run func(ctx context.Context, params repository.RevokeSessionParams)) *MockSessionRepository_RevokeSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.RevokeSessionParams
		if args[1] != nil {
			arg1 = args[1].(repository.RevokeSessionParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_RevokeSession_Call) Return(err error) *MockSessionRepository_RevokeSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_RevokeSession_Call) RunAndReturn(run func(ctx context.Context, params repository.RevokeSessionParams) error) *MockSessionRepository_RevokeSession_Call {
	_c.Call.Return(run)
	return _c
}
