// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testmock

import (
	mock "github.com/stretchr/testify/mock"
	"saviour/internal/service/auth"
)

// NewMockTokenValidator creates a new instance of MockTokenValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenValidator {
	mock := &MockTokenValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenValidator is an autogenerated mock type for the TokenValidator type
type MockTokenValidator struct {
	mock.Mock
}

type MockTokenValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenValidator) EXPECT() *MockTokenValidator_Expecter {
	return &MockTokenValidator_Expecter{mock: &_m.Mock}
}

// ValidateAccessToken provides a mock function for the type MockTokenValidator
func (_mock *MockTokenValidator) ValidateAccessToken(token string) (*auth.TokenParsed, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *auth.TokenParsed
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*auth.TokenParsed, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *auth.TokenParsed); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.TokenParsed)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenValidator_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockTokenValidator_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - token string
func (_e *MockTokenValidator_Expecter) ValidateAccessToken(token interface{}) *MockTokenValidator_ValidateAccessToken_Call {
	return &MockTokenValidator_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", token)}
}

func (_c *MockTokenValidator_ValidateAccessToken_Call) Run(run func(token string)) *MockTokenValidator_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenValidator_ValidateAccessToken_Call) Return(tokenParsed *auth.TokenParsed, err error) *MockTokenValidator_ValidateAccessToken_Call {
	_c.Call.Return(tokenParsed, err)
	return _c
}

func (_c *MockTokenValidator_ValidateAccessToken_Call) RunAndReturn(run func(token string) (*auth.TokenParsed, error)) *MockTokenValidator_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRefreshToken provides a mock function for the type MockTokenValidator
func (_mock *MockTokenValidator) ValidateRefreshToken(token string) (*auth.TokenParsed, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshToken")
	}

	var r0 *auth.TokenParsed
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*auth.TokenParsed, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *auth.TokenParsed); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.TokenParsed)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenValidator_ValidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRefreshToken'
type MockTokenValidator_ValidateRefreshToken_Call struct {
	*mock.Call
}

// ValidateRefreshToken is a helper method to define mock.On call
//   - token string
func (_e *MockTokenValidator_Expecter) ValidateRefreshToken(token interface{}) *MockTokenValidator_ValidateRefreshToken_Call {
	return &MockTokenValidator_ValidateRefreshToken_Call{Call: _e.mock.On("ValidateRefreshToken", token)}
}

func (_c *MockTokenValidator_ValidateRefreshToken_Call) Run(run func(token string)) *MockTokenValidator_ValidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenValidator_ValidateRefreshToken_Call) Return(tokenParsed *auth.TokenParsed, err error) *MockTokenValidator_ValidateRefreshToken_Call {
	_c.Call.Return(tokenParsed, err)
	return _c
}

func (_c *MockTokenValidator_ValidateRefreshToken_Call) RunAndReturn(run func(token string) (*auth.TokenParsed, error)) *MockTokenValidator_ValidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
