// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testmock

import (
	"context"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"saviour/internal/model"
	"saviour/internal/service/user"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the Service type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockUserService
func (_mock *MockUserService) CreateUser(ctx context.Context, params user.CreateUserParams) (*model.User, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.CreateUserParams) (*model.User, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.CreateUserParams) *model.User); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.CreateUserParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - params user.CreateUserParams
func (_e *MockUserService_Expecter) CreateUser(ctx interface{}, params interface{}) *MockUserService_CreateUser_Call {
	return &MockUserService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, params)}
}

func (_c *MockUserService_CreateUser_Call) Run(run func(ctx context.Context, params user.CreateUserParams)) *MockUserService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.CreateUserParams
		if args[1] != nil {
			arg1 = args[1].(user.CreateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_CreateUser_Call) Return(user1 *model.User, err error) *MockUserService_CreateUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserService_CreateUser_Call) RunAndReturn(run func(ctx context.Context, params user.CreateUserParams) (*model.User, error)) *MockUserService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeactivateUser provides a mock function for the type MockUserService
func (_mock *MockUserService) DeactivateUser(ctx context.Context, uuid1 uuid.UUID) error {
	ret := _mock.Called(ctx, uuid1)

	if len(ret) == 0 {
		panic("no return value specified for DeactivateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, uuid1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserService_DeactivateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeactivateUser'
type MockUserService_DeactivateUser_Call struct {
	*mock.Call
}

// DeactivateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid1 uuid.UUID
func (_e *MockUserService_Expecter) DeactivateUser(ctx interface{}, uuid1 interface{}) *MockUserService_DeactivateUser_Call {
	return &MockUserService_DeactivateUser_Call{Call: _e.mock.On("DeactivateUser", ctx, uuid1)}
}

func (_c *MockUserService_DeactivateUser_Call) Run(run func(ctx context.Context, uuid1 uuid.UUID)) *MockUserService_DeactivateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_DeactivateUser_Call) Return(err error) *MockUserService_DeactivateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserService_DeactivateUser_Call) RunAndReturn(run func(ctx context.Context, uuid1 uuid.UUID) error) *MockUserService_DeactivateUser_Call {
	_c.Call.Return(run)
	return _c
}
