// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package testmock

import (
	"context"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
	"saviour/internal/model"
	"saviour/internal/repository"
)

// NewMockWorkspaceRepository creates a new instance of MockWorkspaceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkspaceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkspaceRepository {
	mock := &MockWorkspaceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkspaceRepository is an autogenerated mock type for the WorkspaceRepository type
type MockWorkspaceRepository struct {
	mock.Mock
}

type MockWorkspaceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkspaceRepository) EXPECT() *MockWorkspaceRepository_Expecter {
	return &MockWorkspaceRepository_Expecter{mock: &_m.Mock}
}

// AddUserToWorkspace provides a mock function for the type MockWorkspaceRepository
func (_mock *MockWorkspaceRepository) AddUserToWorkspace(ctx context.Context, userUUID uuid.UUID, workspaceUUID uuid.UUID) error {
	ret := _mock.Called(ctx, userUUID, workspaceUUID)

	if len(ret) == 0 {
		panic("no return value specified for AddUserToWorkspace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userUUID, workspaceUUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkspaceRepository_AddUserToWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserToWorkspace'
type MockWorkspaceRepository_AddUserToWorkspace_Call struct {
	*mock.Call
}

// AddUserToWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
//   - workspaceUUID uuid.UUID
func (_e *MockWorkspaceRepository_Expecter) AddUserToWorkspace(ctx interface{}, userUUID interface{}, workspaceUUID interface{}) *MockWorkspaceRepository_AddUserToWorkspace_Call {
	return &MockWorkspaceRepository_AddUserToWorkspace_Call{Call: _e.mock.On("AddUserToWorkspace", ctx, userUUID, workspaceUUID)}
}

func (_c *MockWorkspaceRepository_AddUserToWorkspace_Call) Run(run func(ctx context.Context, userUUID uuid.UUID, workspaceUUID uuid.UUID)) *MockWorkspaceRepository_AddUserToWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWorkspaceRepository_AddUserToWorkspace_Call) Return(err error) *MockWorkspaceRepository_AddUserToWorkspace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkspaceRepository_AddUserToWorkspace_Call) RunAndReturn(run func(ctx context.Context, userUUID uuid.UUID, workspaceUUID uuid.UUID) error) *MockWorkspaceRepository_AddUserToWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWorkspace provides a mock function for the type MockWorkspaceRepository
func (_mock *MockWorkspaceRepository) CreateWorkspace(ctx context.Context, params repository.CreateWorkspaceParams) (*model.Workspace, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkspace")
	}

	var r0 *model.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CreateWorkspaceParams) (*model.Workspace, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.CreateWorkspaceParams) *model.Workspace); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Workspace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.CreateWorkspaceParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceRepository_CreateWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkspace'
type MockWorkspaceRepository_CreateWorkspace_Call struct {
	*mock.Call
}

// CreateWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - params repository.CreateWorkspaceParams
func (_e *MockWorkspaceRepository_Expecter) CreateWorkspace(ctx interface{}, params interface{}) *MockWorkspaceRepository_CreateWorkspace_Call {
	return &MockWorkspaceRepository_CreateWorkspace_Call{Call: _e.mock.On("CreateWorkspace", ctx, params)}
}

func (_c *MockWorkspaceRepository_CreateWorkspace_Call) Run(run func(ctx context.Context, params repository.CreateWorkspaceParams)) *MockWorkspaceRepository_CreateWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.CreateWorkspaceParams
		if args[1] != nil {
			arg1 = args[1].(repository.CreateWorkspaceParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkspaceRepository_CreateWorkspace_Call) Return(workspace *model.Workspace, err error) *MockWorkspaceRepository_CreateWorkspace_Call {
	_c.Call.Return(workspace, err)
	return _c
}

func (_c *MockWorkspaceRepository_CreateWorkspace_Call) RunAndReturn(run func(ctx context.Context, params repository.CreateWorkspaceParams) (*model.Workspace, error)) *MockWorkspaceRepository_CreateWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// DoesUserBelongToWorkspace provides a mock function for the type MockWorkspaceRepository
func (_mock *MockWorkspaceRepository) DoesUserBelongToWorkspace(ctx context.Context, userUUID uuid.UUID, workspaceUUID uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, userUUID, workspaceUUID)

	if len(ret) == 0 {
		panic("no return value specified for DoesUserBelongToWorkspace")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, userUUID, workspaceUUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, userUUID, workspaceUUID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userUUID, workspaceUUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceRepository_DoesUserBelongToWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoesUserBelongToWorkspace'
type MockWorkspaceRepository_DoesUserBelongToWorkspace_Call struct {
	*mock.Call
}

// DoesUserBelongToWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
//   - workspaceUUID uuid.UUID
func (_e *MockWorkspaceRepository_Expecter) DoesUserBelongToWorkspace(ctx interface{}, userUUID interface{}, workspaceUUID interface{}) *MockWorkspaceRepository_DoesUserBelongToWorkspace_Call {
	return &MockWorkspaceRepository_DoesUserBelongToWorkspace_Call{Call: _e.mock.On("DoesUserBelongToWorkspace", ctx, userUUID, workspaceUUID)}
}

func (_c *MockWorkspaceRepository_DoesUserBelongToWorkspace_Call) Run(run func(ctx context.Context, userUUID uuid.UUID, workspaceUUID uuid.UUID)) *MockWorkspaceRepository_DoesUserBelongToWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWorkspaceRepository_DoesUserBelongToWorkspace_Call) Return(b bool, err error) *MockWorkspaceRepository_DoesUserBelongToWorkspace_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockWorkspaceRepository_DoesUserBelongToWorkspace_Call) RunAndReturn(run func(ctx context.Context, userUUID uuid.UUID, workspaceUUID uuid.UUID) (bool, error)) *MockWorkspaceRepository_DoesUserBelongToWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUserFromWorkspace provides a mock function for the type MockWorkspaceRepository
func (_mock *MockWorkspaceRepository) RemoveUserFromWorkspace(ctx context.Context, userUUID uuid.UUID, workspaceUUID uuid.UUID) error {
	ret := _mock.Called(ctx, userUUID, workspaceUUID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUserFromWorkspace")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userUUID, workspaceUUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkspaceRepository_RemoveUserFromWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUserFromWorkspace'
type MockWorkspaceRepository_RemoveUserFromWorkspace_Call struct {
	*mock.Call
}

// RemoveUserFromWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
//   - workspaceUUID uuid.UUID
func (_e *MockWorkspaceRepository_Expecter) RemoveUserFromWorkspace(ctx interface{}, userUUID interface{}, workspaceUUID interface{}) *MockWorkspaceRepository_RemoveUserFromWorkspace_Call {
	return &MockWorkspaceRepository_RemoveUserFromWorkspace_Call{Call: _e.mock.On("RemoveUserFromWorkspace", ctx, userUUID, workspaceUUID)}
}

func (_c *MockWorkspaceRepository_RemoveUserFromWorkspace_Call) Run(run func(ctx context.Context, userUUID uuid.UUID, workspaceUUID uuid.UUID)) *MockWorkspaceRepository_RemoveUserFromWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWorkspaceRepository_RemoveUserFromWorkspace_Call) Return(err error) *MockWorkspaceRepository_RemoveUserFromWorkspace_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkspaceRepository_RemoveUserFromWorkspace_Call) RunAndReturn(run func(ctx context.Context, userUUID uuid.UUID, workspaceUUID uuid.UUID) error) *MockWorkspaceRepository_RemoveUserFromWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWorkspace provides a mock function for the type MockWorkspaceRepository
func (_mock *MockWorkspaceRepository) UpdateWorkspace(ctx context.Context, workspaceUUID uuid.UUID, params repository.UpdateWorkspaceParams) (*model.Workspace, error) {
	ret := _mock.Called(ctx, workspaceUUID, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkspace")
	}

	var r0 *model.Workspace
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, repository.UpdateWorkspaceParams) (*model.Workspace, error)); ok {
		return returnFunc(ctx, workspaceUUID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, repository.UpdateWorkspaceParams) *model.Workspace); ok {
		r0 = returnFunc(ctx, workspaceUUID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Workspace)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, repository.UpdateWorkspaceParams) error); ok {
		r1 = returnFunc(ctx, workspaceUUID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceRepository_UpdateWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkspace'
type MockWorkspaceRepository_UpdateWorkspace_Call struct {
	*mock.Call
}

// UpdateWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceUUID uuid.UUID
//   - params repository.UpdateWorkspaceParams
func (_e *MockWorkspaceRepository_Expecter) UpdateWorkspace(ctx interface{}, workspaceUUID interface{}, params interface{}) *MockWorkspaceRepository_UpdateWorkspace_Call {
	return &MockWorkspaceRepository_UpdateWorkspace_Call{Call: _e.mock.On("UpdateWorkspace", ctx, workspaceUUID, params)}
}

func (_c *MockWorkspaceRepository_UpdateWorkspace_Call) Run(run func(ctx context.Context, workspaceUUID uuid.UUID, params repository.UpdateWorkspaceParams)) *MockWorkspaceRepository_UpdateWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 repository.UpdateWorkspaceParams
		if args[2] != nil {
			arg2 = args[2].(repository.UpdateWorkspaceParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWorkspaceRepository_UpdateWorkspace_Call) Return(workspace *model.Workspace, err error) *MockWorkspaceRepository_UpdateWorkspace_Call {
	_c.Call.Return(workspace, err)
	return _c
}

func (_c *MockWorkspaceRepository_UpdateWorkspace_Call) RunAndReturn(run func(ctx context.Context, workspaceUUID uuid.UUID, params repository.UpdateWorkspaceParams) (*model.Workspace, error)) *MockWorkspaceRepository_UpdateWorkspace_Call {
	_c.Call.Return(run)
	return _c
}
