openapi: "3.0.0"
info:
  version: 0.0.1
  title: Saviour API
  description: "API reference"

servers:
  - url: http://localhost:8080/api

security:
  - BearerAuth: []

x-error-responses:
  validation-error-response: &validation-error-response
    "400":
      description: request validation failed error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ValidationErrorResponse"
  authentication-error-response: &authentication-error-response
    "401":
      description: authentication error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AuthenticationErrorResponse"
  access-forbidden-error-response: &access-forbidden-error-response
    "403":
      description: access to resource forbidden error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/AccessForbiddenErrorResponse"
  not-found-error-response: &not-found-error-response
    "404":
      description: entity not found error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/EntityNotFoundErrorResponse"
  server-error-response: &server-error-response
    "500":
      description: server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
  timeout-error-response: &timeout-error-response
    "504":
      description: response timeout error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/TimeoutErrorResponse"

tags:
  - name: health
    description: API server's health operations
  - name: authentication
    description: Session operations
  - name: users
    description: User operations
  - name: workspaces
    description: Workspace operations
  - name: secrets
    description: Secret operations
  - name: sources
    description: Backup source operations
  - name: storages
    description: Backup storage operations
  - name: pipelines
    description: Backup pipeline operations

paths:
  "/ping":
    get:
      summary: Ping the API server
      description: Can be used for a healthcheck
      security: []
      tags:
        - health
      operationId: ping
      responses:
        "200":
          description: ping response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PingResponse"
        <<: [
          *timeout-error-response,
          *server-error-response,
        ]
  "/auth/sessions":
    post:
      summary: Create a new session
      description: Create a new session
      tags:
        - authentication
      security: [ ]
      operationId: create_session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSessionRequest"
      responses:
        "200":
          description: create session response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessTokenResponse"
        "401":
          description: invalid credentials error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateSessionErrorResponse"
        <<: [
          *validation-error-response,
          *timeout-error-response,
          *server-error-response,
        ]
  "/auth/sessions/refresh":
    post:
      summary: Refresh the current session
      description: Refresh the current session. Refresh token is extracted from cookies
      security:
        - RefreshTokenCookie: [ ]
      tags:
        - authentication
      operationId: refresh_session
      responses:
        "200":
          description: refresh session response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessTokenResponse"
        "401":
          description: refresh session error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RefreshSessionErrorResponse"
        <<: [
          *not-found-error-response,
          *timeout-error-response,
          *server-error-response,
        ]
  "/auth/sessions/{session_id}/revoke":
    post:
      summary: Revoke a session
      description: Revoke a session
      tags:
        - authentication
      operationId: revoke_session
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        "200":
          description: revoke session response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmptyResponse"
        <<: [
          *validation-error-response,
          *authentication-error-response,
          *not-found-error-response,
          *timeout-error-response,
          *server-error-response,
        ]
  "/users":
    post:
      summary: Create a user
      description: Create a user
      tags:
        - users
      security:
        - BearerAuth: [ admin ]
      operationId: create_user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequest"
      responses:
        "200":
          description: user response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserResponse"
        <<: [
          *validation-error-response,
          *authentication-error-response,
          *access-forbidden-error-response,
          *timeout-error-response,
          *server-error-response,
        ]
  "/users/{user_uuid}/deactivate":
    post:
      summary: Deactivate a user
      description: Deactivate a user
      tags:
        - users
      security:
        - BearerAuth: [ admin ]
      operationId: deactivate_user
      parameters:
        - name: user_uuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        "200":
          description: user deactivated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmptyResponse"
        <<: [
          *validation-error-response,
          *authentication-error-response,
          *access-forbidden-error-response,
          *not-found-error-response,
          *timeout-error-response,
          *server-error-response,
        ]
  "/workspaces":
    post:
      summary: Create a workspace
      description: Create a user
      tags:
        - workspaces
      security:
        - BearerAuth: [ admin ]
      operationId: create_workspace
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateWorkspaceRequest"
      responses:
        "200":
          description: workspace response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkspaceResponse"
        <<: [
          *validation-error-response,
          *authentication-error-response,
          *access-forbidden-error-response,
          *timeout-error-response,
          *server-error-response,
        ]
  "/workspaces/{workspace_uuid}":
    put:
      summary: Update a workspace
      description: Update a user
      tags:
        - workspaces
      security:
        - BearerAuth: [ admin ]
      operationId: update_workspace
      parameters:
        - name: workspace_uuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateWorkspaceRequest"
      responses:
        "200":
          description: workspace response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkspaceResponse"
        <<: [
          *validation-error-response,
          *authentication-error-response,
          *access-forbidden-error-response,
          *not-found-error-response,
          *timeout-error-response,
          *server-error-response,
        ]
  "/workspaces/{workspace_uuid}/users":
    post:
      summary: Add a user to a workspace
      description: Add a user to a workspace
      tags:
        - workspaces
      security:
        - BearerAuth: [ admin ]
      operationId: add_user_to_workspace
      parameters:
        - name: workspace_uuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddUserToWorkspaceRequest"
      responses:
        "200":
          description: user added response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmptyResponse"
        <<: [
          *validation-error-response,
          *authentication-error-response,
          *access-forbidden-error-response,
          *not-found-error-response,
          *timeout-error-response,
          *server-error-response,
        ]
  "/workspaces/{workspace_uuid}/users/{user_uuid}":
    delete:
      summary: Remove a user from a workspace
      description: Remove a user from a workspace
      tags:
        - workspaces
      security:
        - BearerAuth: [ admin ]
      operationId: remove_user_from_workspace
      parameters:
        - name: workspace_uuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
        - name: user_uuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        "204":
          description: user removed from workspace
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmptyResponse"
        <<: [
          *validation-error-response,
          *authentication-error-response,
          *access-forbidden-error-response,
          *timeout-error-response,
          *server-error-response,
        ]
  "/workspaces/{workspace_uuid}/secrets":
    post:
      summary: Create a secret
      description: Create a secret
      tags:
        - secrets
      operationId: create_secret
      parameters:
        - name: workspace_uuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateSecretRequest"
      responses:
        "200":
          description: secret response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SecretResponse"
        <<: [
          *validation-error-response,
          *authentication-error-response,
          *access-forbidden-error-response,
          *not-found-error-response,
          *timeout-error-response,
          *server-error-response,
        ]
  "/workspaces/{workspace_uuid}/secrets/{secret_uuid}":
    put:
      summary: Update a secret
      description: Update a secret
      tags:
        - secrets
      operationId: update_secret
      parameters:
        - name: workspace_uuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
        - name: secret_uuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateSecretRequest"
      responses:
        "200":
          description: secret response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SecretResponse"
        <<: [
          *validation-error-response,
          *authentication-error-response,
          *access-forbidden-error-response,
          *not-found-error-response,
          *timeout-error-response,
          *server-error-response,
        ]

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

    RefreshTokenCookie:
      type: apiKey
      in: cookie
      name: refresh_token

  schemas:
    EmptyResponse:
      type: object
      additionalProperties: false

    PingResponse:
      type: object
      properties:
        instance:
          type: string
          description: Name of the server instance
        server_time:
          type: string
          format: date-time
          description: Server time
      required:
        - instance
        - server_time

    CreateSessionRequest:
      type: object
      required: [ username, password ]
      properties:
        username:
          type: string
          pattern: '^[a-z]+$'
          maxLength: 32
        password:
          type: string
          maxLength: 64
          example: "Su6erSecR3T"

    AccessTokenResponse:
      type: object
      required: [ access_token ]
      properties:
        access_token:
          type: string
          description: Short-lived token for accessing protected endpoints

    CreateUserRequest:
      type: object
      required: 
        - username
        - password
      properties:
        username:
          type: string
          description: Must be unique
          pattern: '^[a-z]+$'
          minLength: 5
          maxLength: 32
          example: username
        password:
          type: string
          minLength: 8
          maxLength: 64
          example: "Su6erSecR3T"
        is_admin:
          type: boolean
          default: false

    UserResponse:
      type: object
      required: 
        - uuid
        - created_at
        - username
        - is_admin
      properties:
        uuid:
          $ref: "#/components/schemas/UUID"
        created_at:
          type: string
          format: date-time
        username:
          type: string
          minLength: 5
          example: admin
        is_admin:
          type: boolean
          example: true

    WorkspaceRequestCommon:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          minLength: 4
          maxLength: 64
          example: "Demo App Backups"

    CreateWorkspaceRequest:
      $ref: "#/components/schemas/WorkspaceRequestCommon"

    UpdateWorkspaceRequest:
      $ref: "#/components/schemas/WorkspaceRequestCommon"

    WorkspaceResponse:
      type: object
      required:
        - uuid
        - created_at
        - name
      properties:
        uuid:
          $ref: "#/components/schemas/UUID"
        created_at:
          type: string
          format: date-time
        name:
          type: string
          minLength: 5
          example: "Demo App Backups"

    AddUserToWorkspaceRequest:
      type: object
      required:
        - user_uuid
      properties:
        user_uuid:
          $ref: "#/components/schemas/UUID"

    SecretRequestCommon:
      type: object
      required:
        - name
        - value
      properties:
        name:
          type: string
          minLength: 4
          maxLength: 64
          example: "Google API key"
        value:
          type: string
          minLength: 1
          description: Secret value to store. It'll be encrypted and never displayed as is
          example: "my_secret_value"

    CreateSecretRequest:
      $ref: "#/components/schemas/SecretRequestCommon"

    UpdateSecretRequest:
      $ref: "#/components/schemas/SecretRequestCommon"

    SecretResponse:
      type: object
      required:
        - uuid
        - created_at
        - name
        - author_uuid
      properties:
        uuid:
          $ref: "#/components/schemas/UUID"
        created_at:
          type: string
          format: date-time
        name:
          type: string
          example: "Google API key"
        author_uuid:
          $ref: "#/components/schemas/UUID"

    UUID:
      type: string
      format: uuid

    ErrorResponse:
      required: [ error ]
      properties:
        error:
          type: object
          required: [ type, status_code ]
          properties:
            type:
              type: string
              example: EXAMPLE_ERROR_TYPE
              description: Identifier of the error type
            status_code:
              type: integer
              format: int32
              description: HTTP status code
            message:
              type: string
              description: Error message
              example: Error message

    ValidationErrorResponse:
      allOf:
        - $ref: "#/components/schemas/ErrorResponse"
        - type: object
          properties:
            error:
              properties:
                type:
                  enum: [ VALIDATION_FAILED ]
                  example: VALIDATION_FAILED

    AuthenticationErrorResponse:
      allOf:
        - $ref: "#/components/schemas/ErrorResponse"
        - type: object
          properties:
            error:
              properties:
                type:
                  enum:
                    - ACCESS_TOKEN_NOT_VALID
                    - ACCESS_TOKEN_EXPIRED
                  example: ACCESS_TOKEN_NOT_VALID

    AccessForbiddenErrorResponse:
      allOf:
        - $ref: "#/components/schemas/ErrorResponse"
        - type: object
          properties:
            error:
              properties:
                type:
                  enum:
                    - ACCESS_FORBIDDEN
                  example: ACCESS_FORBIDDEN

    CreateSessionErrorResponse:
      allOf:
        - $ref: "#/components/schemas/ErrorResponse"
        - type: object
          properties:
            error:
              properties:
                type:
                  enum: [ INVALID_CREDENTIALS ]
                  example: INVALID_CREDENTIALS

    RefreshSessionErrorResponse:
      allOf:
        - $ref: "#/components/schemas/ErrorResponse"
        - type: object
          properties:
            error:
              properties:
                type:
                  enum:
                    - REFRESH_TOKEN_NOT_SET
                    - REFRESH_TOKEN_NOT_VALID
                    - REFRESH_TOKEN_EXPIRED
                  example: REFRESH_TOKEN_NOT_VALID

    EntityNotFoundErrorResponse:
      allOf:
        - $ref: "#/components/schemas/ErrorResponse"
        - type: object
          properties:
            error:
              properties:
                type:
                  enum: [ ENTITY_NOT_FOUND ]
                  example: ENTITY_NOT_FOUND

    TimeoutErrorResponse:
      allOf:
        - $ref: "#/components/schemas/ErrorResponse"
        - type: object
          properties:
            error:
              properties:
                type:
                  enum: [ RESPONSE_TIMEOUT ]
                  example: RESPONSE_TIMEOUT
